### ISSUE TITLE
Remplacer les composant arrow functions par des fonctions nommées

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#1002]
## Contexte
Certains composant sont encore défini par des "arrow functions", hors le rechargement rapide ne préserve pas les `states` de ces composants. 

### Avant
`export default () => <div />`

### Après
```
const Named = () => <div />
export default Named
```

**Comment by zakariazuck** [comment]
Salut @tmerlier , puis-je obtenir la permission de résoudre ce problème?

**Comment by GllmR** [comment]
Le seul composant fléché trouvé est dans le hoc `withError` .
Lorsqu'on le modifie pour une fonction nommée, le composant ne fonctionne plus.
