### ISSUE TITLE
Ajouter un bandeau sur le site pour annoncer des formations / adresse labs / ...

### ISSUE THREAD

**Issue by Ariane-Rose** [BaseAdresseNationale/adresse.data.gouv.fr#1018]

**Comment by C-Sophie** [comment]
Si besoin de wording, voici les EDL issus de l'infolettre (car pas de formulaire d'inscription ni de proposition de niveaux)

L'équipe du Programme Bases Adresses Locales propose aux communes qui le souhaitent un webinaire sur l'éditeur [Mes Adresses](https://mes-adresses.data.gouv.fr/). Au menu, un rappel des principales fonctionnalités et les points de vigilance #qualité.
Pour participer : il suffit d'écrire par retour de mail à adresse@data.gouv.fr avec en objet "Webinaire du 10 mars". Précisez vos nom et qualité et éventuellement un point que vous souhaitez approfondir.
