### ISSUE TITLE
Améliorer la recherche sur https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees ?

### ISSUE THREAD

**Issue by ThomasG77** [BaseAdresseNationale/adresse.data.gouv.fr#1021]
Sur <https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees>, la recherche ne permet la recherche que par nom du porteur de la BAL et pas par commune.

Il n'est pas possible actuellement de chercher directement par nom de commune dès que c'est une EPCI qui porte la BAL pour ses communes.

**Exemple de scénario**:

- J'arrive sur https://adresse.data.gouv.fr/bases-locales
- Je vais sur sur le lien [Voir toutes les Bases Adresses Locales](https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees)
- Je cherche Bouguenais qui fait partie de la l'EPCI Nantes Métropole. Je ne trouve rien.
- Pour trouver la commune, je dois deviner qu'il faut chercher le nom de l'EPCI. En partant de là, je cherche Nantes et je trouve la BAL de Nantes Métropole <https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees/5d6f01d906e3e71f6bd78afd>.
- Je clique dessus et je peux maintenant chercher dans la liste des communes Bouguenais et la trouver enfin

De ce point de vue, la page https://adresse.data.gouv.fr/deploiement-bal (je n'ai pas retrouvé comment accéder à cette URL) permet de pallier au problème partiellement en évitant la question des communes car on peut passer par la carte.

**Comment by jdesboeufs** [comment]
Tu as depuis hier une nouvelle section en page d'accueil qui permet de chercher une commune

<img width="1244" alt="Capture d’écran 2022-02-09 à 14 29 28" src="https://user-images.githubusercontent.com/1231232/153210940-e3f1dcfb-f19a-4060-988a-a0062ace5814.png">

À très court terme le lien avec les BAL moissonnées sera fait.

**Comment by jdesboeufs** [comment]
Quant à deploiement-bal on y accède par la page d'accueil, dans un bandeau, et via la page Bases Adresses Locales.

**Comment by ThomasG77** [comment]
Pour info, j'avais besoin d'un GeoJSON des zones couvertes par les BAL, j'ai pompé vos end-point datasets et retransformé en GeoJSON https://gist.github.com/ThomasG77/e6643b4e6d13daf7753f08e9a9c87e21
Je ne sais pas si ça peut servir. A poster sur l'orga BAN de data.gouv.fr?

**Comment by jdesboeufs** [comment]
Cette route d'API va bientôt être supprimée.
On y pensera pour la suite.
On a déjà un CSV mais pas de GeoJSON.

**Comment by ThomasG77** [comment]
> On a déjà un CSV mais pas de GeoJSON.

Public? Pas identifié.

**Comment by jdesboeufs** [comment]
https://www.data.gouv.fr/fr/datasets/etat-de-la-base-adresse-nationale-par-commune/

**Comment by mmortier** [comment]
Les pages de consultation du déploiement des BAL ont été refondues suite à la livraison du moissonneurV2. Ce n'est plus d'actualité. Je clos le ticket
