### ISSUE TITLE
Ajouter une ancre pour https://adresse.data.gouv.fr/contribuer

### ISSUE THREAD

**Issue by ThomasG77** [BaseAdresseNationale/adresse.data.gouv.fr#1026]
Besoin pour référencer en particulier "En tant que citoyen" parmi les balises `<h2>`

- En tant que commune
- En tant que citoyen
- En tant qu’utilisateur des données

Similaire à #1024

**Comment by Maxine-Le-Pennec** [comment]
> Besoin pour référencer en particulier "En tant que citoyen" parmi les balises `<h2>`
> 
> * En tant que commune
> * En tant que citoyen
> * En tant qu’utilisateur des données
> 
> Similaire à #1024

Amélioration apportée. Il est désormais possible d'accéder aux sections : 

- **En tant que commune**, via l'url => `https://adresse.data.gouv.fr/contribuer#commune`
- **En tant que citoyen,** via l'url => `https://adresse.data.gouv.fr/contribuer#citoyen`
- **En tant qu’utilisateur des données**, via l'url => `https://adresse.data.gouv.fr/contribuer#utilisateur`

**Comment by ThomasG77** [comment]
Merci
