### ISSUE TITLE
Harmonisation BAL vs. BAN pour l'affichage des numéros à plusieurs positions

### ISSUE THREAD

**Issue by rstadel** [BaseAdresseNationale/adresse.data.gouv.fr#1036]
L'éditeur utilise la première des entrées de la liste des positions d'un numéro pour situer ce numéro sur la carte (s'il y a plusieurs positions), alors que la BAN semble utiliser la dernière -> pourrait-on harmoniser cela pour avoir plus de précision sur les points données ?

Illustration ci-dessous BAL vs. BAN (2nde image vs. 3e image) sur une adresse avec trois positions associées (dans l’ordre en Entrée, Délivrance Postale et Bâtiment, cf 1ère image) -> La BAL utilise l’Entrée, alors que la BAN utilise le Bâtiment pour situer le point sur la carte ; personnellement l’interprétation BAL est plus justifiée, peut-être faudrait-il conventionner ceci dans la spécification.

![pj1](https://user-images.githubusercontent.com/33312469/130073244-0f803899-6bef-4eb3-ae69-293b36503d9b.png)
![pj2](https://user-images.githubusercontent.com/33312469/130073248-40e2e170-2ad8-47e2-a9d7-46a3920e2ca3.png)
![pj3](https://user-images.githubusercontent.com/33312469/130073249-bfbd64be-749e-4b51-a2af-fc8533b93b5b.png)

**Comment by tmerlier** [comment]
Ticket reporté sur #1000
