### ISSUE TITLE
Fonctionnalité d'ajout d'un évènement au calendrier

### ISSUE THREAD

**Issue by Maxine-Le-Pennec** [BaseAdresseNationale/adresse.data.gouv.fr#1040]
Fonctionnalité soumise et ajoutée en utilisant le package [add-to-calendar-button](https://jekuer.github.io/add-to-calendar-button/) de jekuer mais retirée pour les raisons suivantes : 

- Package trop récent et peu utilisé.
- Pas d'adaptation "propre" à une utilisation React-friendly

La solution principale retenue serait de forker le projet et modifier le code afin d'obtenir une version correctement utilisable dans un projet React ou de développer la fonctionnalité nous même.

Commit de suppression de la fonctionnalité : _5ebc071ce0ad50960182d1faa2734a2402f1a643_ sur la branche **Max/event-page**

**Comment by mmortier** [comment]
La gestion des évènements est faite autrement
