### ISSUE TITLE
Ajouter une section flux de données à la page données nationales

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1051]
ajouter sous télécharger un section avec 3 cartes  : 
WMS / WFS / WMTS avec un descriptif.
maquette à venir

**Comment by mmortier** [comment]
![maquette_flux_1051](https://user-images.githubusercontent.com/7045982/156005584-9e7385fb-0d20-4802-a265-7530081c4208.png)

maquette pour l'ajout des flux dans la page Données nationales

Question : quand on parle du WMTS qui est dispo on parle de quel lien? Où alors on parle de la route de chargement des tiles pbf /tiles/ban/{z}/{x}/{y}.pbf ?

**Comment by jdesboeufs** [comment]
Plusieurs suggestions :
- délimiter visuellement la section (autre coloris, on a du style adapté normalement dans le projet Adresse cc @Maxine-Le-Pennec @tmerlier)
- Avoir un paragraphe de texte qui explique de quoi on parle (un flux est un terme technique qui n'est trivial que pour une partie de notre public, il faut aussi indiquer qu'on parle de représentation cartographique)
- Pourquoi pas réutiliser les cartes, mais dans ce cas on peut donner plus de détails : fréquence de mise à jour, lien vers documentation éventuelle (à créer peut-être), version du protocole)

Concernant les tuiles vectorielles :
- Format : MVT (Mapbox Vector Tiles)
- Type de flux : XYZ
- Fréquence de mise à jour : temps réel
- URL : https://plateforme.adresse.data.gouv.fr/tiles/ban/{z}/{x}/{y}.pbf

Il faudrait qu'on documente aussi ce dernier flux et qu'on propose 1) un style par défaut 2) un fichier TileJSON

**Comment by FrederiqWilliams** [comment]
Suggestions : 
- "Services cartographiques" plutôt que "flux de données" pour le titre. 
- regrouper dans la même section les deux flux WFS et WMS. 
- mettre le flux WFS en premier

description : " Les services WFS et WMS permettent à des utilisateurs distants de télécharger des données, via une simple requête HTTPS, à partir des données sources adresse BAN vecteur. Les données obtenues sont sous forme vecteur (WFS) ou image (WMS) géoréférencées.
Fréquence de mise à jour : hebdomadaire. 
WFS et WMS sont des protocoles standards définis par l’OGC (Open Geospatial Consortium) et reconnus par une norme ISO. On peut consulter le document de référence sur [le site de l’OGC](http://www.opengeospatial.org/standards/wfs). Les services proposés ici implémentent la version 2.0 de ce protocole."

**Comment by mmortier** [comment]
![maquette_flux_1051_v2](https://user-images.githubusercontent.com/7045982/156797313-b92264f7-53d4-4fb0-b6c9-ef5d6bf82315.png)
Je propose une nouvelle maquette. Les liens pointent  : 
carte 1 et 2  : https://geoservices.ign.fr/services-web-experts-adresse
carte 3 : https://github.com/BaseAdresseNationale/ban-plateforme/wiki/Documentation-API-de-consultation-BAN 
Il faudra sans doute plus détailler dans la doc du wiki ce qui concerne les tuiles vectorielles.

@FrederiqWilliams je ne pense pas mettre les flux WMS et WFS ensemble car comme les URL et les noms des couches ne sont pas les mêmes. Je me dit que garder 2 cartes n'est pas gênant. A voir avec le reste de l'équipe...

**Comment by jdesboeufs** [comment]
Merci.
Je passe la main à @tmerlier et @Maxine-Le-Pennec pour le rendu :)

Sinon pourquoi indiquer WMS "vecteur" ? Ce sont des formats images qui sont retournés. WMS tout court ça ne suffit pas ?
