### ISSUE TITLE
Ajouter le témoignage de Rougon sur la page des Témoignages

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1066]
Sur la page : https://adresse.data.gouv.fr/bases-locales/temoignages

Titre : Rougon

Petit résumé : 
Petit village de 116 habitants, Rougon s’est doté d’une Base Adresse Locale complète alors qu’aucune adresse n’était référencée. Gilles Bossuet, conseiller municipal détaille une démarche vertueuse qui aboutit à 100% des adresses certifiées avec les parcelles cadastrales renseignées.
![66e0e1fa3efc4d608deea238407ce34d](https://user-images.githubusercontent.com/69309231/156614049-1ff63043-6ec6-4b8b-963e-1d99b0999df6.jpg)

**Comment by Maxine-Le-Pennec** [comment]
Doublon
