### ISSUE TITLE
Supprimer les tags "diffusion" et "animation" des partenaires

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#1113]
## Contexte
Le système de filtre pour les partenaires comporte actuellement les tags `diffusion` et `animation`. Cependant, l'animation est un critère qui concerne tous les partenaires et la diffusion est gérée par la BAN. Ces tags n'ont donc pas lieu d'être et peuvent être supprimés.

## Champ "infos" à revoir
Liste des partenaires dont le champ `infos` comporte les mots `animation` ou `diffusion`
- [ ] Colmar Agglomération
- [ ] Anne Légaut
- [ ] SIGEO 3D
- [ ] Pays de Brest
- [ ] Communauté d’Agglomération Pays Basque
- [ ] Réseau Régional des Données Territoriales et Géographiques en Centre-Val de Loire

**Comment by C-Sophie** [comment]
Mots-clés, prévenir :
- [ ] ATD16 (animation, diffusion) 
- [ ] ARC (diffusion)
- [ ] Colmar Agglomération (diffusion, animation)
- [ ] Communauté de Communes des Lisières de l’Oise (diffusion)
- [ ] Communauté de Communes du Pont du Gard (animation)
- [ ] Communauté d’Agglomération Pau Béarn Pyrénées Atlantiques (animation)
- [ ] Communauté d’agglomération Roannais Agglomération (animation)
- [ ] GeoPal (animation, diffusion)
- [ ] IdéoBFC (animation, formation)
- [ ] Pays de Brest (animation, diffusion)
- [ ] Réseau Régional des Données Territoriales et Géographiques en Centre-Val de Loire (animation diffusion)
- [ ] Tigeo (diffusion)
