### ISSUE TITLE
Carte interactive : capturer le XY d'un point 

### ISSUE THREAD

**Issue by kqueekquee** [BaseAdresseNationale/adresse.data.gouv.fr#1121]
serait il possible de disposer sur la carte interactive d'une fonction permettant de cliquer sur l'écran + pour obtenir la position XY de ce point et copier dans le presse papier

![HOLLAENDER_2022-04-09_12-50-02](https://user-images.githubusercontent.com/921519/162568766-47a36d65-6b23-493b-87c1-4ab0d8fc5612.jpg)

**Comment by jdesboeufs** [comment]
Bonjour

Quel est le rapport avec notre outil ? C'est pour aider à l'adressage ?

**Comment by mmortier** [comment]
en l'absence de réponse je clos le ticket
