### ISSUE TITLE
Afficher les langues régionales dans l'explorateur BAN

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/adresse.data.gouv.fr#1126]
Contexte : https://github.com/BaseAdresseNationale/ban-bal/issues/1
Pré-requis : https://github.com/BaseAdresseNationale/ban-plateforme/issues/17

Quand les libellés en langues régionales seront disponibles, il faudra les afficher dans l'explorateur.
On peut d'ores et déjà travailler sur la forme et l'UX.

@Maxine-Le-Pennec ça t'intéresse ?

**Comment by Maxine-Le-Pennec** [comment]
> Contexte : [BaseAdresseNationale/ban-bal#1](https://github.com/BaseAdresseNationale/ban-bal/issues/1) Pré-requis : [BaseAdresseNationale/ban-plateforme#17](https://github.com/BaseAdresseNationale/ban-plateforme/issues/17)
> 
> Quand les libellés en langues régionales seront disponibles, il faudra les afficher dans l'explorateur. On peut d'ores et déjà travailler sur la forme et l'UX.
> 
> @Maxine-Le-Pennec ça t'intéresse ?

Oui ça me chauffe

**Comment by jdesboeufs** [comment]
Dupliquée par #1234
