### ISSUE TITLE
Aucun résultat pour certains départements (ex. Alpes Maritimes)

### ISSUE THREAD

**Issue by kinamike** [BaseAdresseNationale/adresse.data.gouv.fr#1178]
Bonjour,

J'ai remarqué que depuis ce matin nous n'avons plus de résultats lors d'une recherche dans le 06 (Alpes Maritimes).

# Exemples

## Sur une adresse dans la Somme (code INSEE 80): 

`https://api-adresse.data.gouv.fr/search/?q=8 Boulevard du Port&postcode=80000`

![Postman sur Amiens](https://user-images.githubusercontent.com/106160198/170036232-fe5de78c-f560-428c-b50e-341a1f6a4c70.png)

Il y a bien des résultats.

## Sur une adresse dans les Alpes Maritimes (code INSEE 06):

`https://api-adresse.data.gouv.fr/search/?q=67 avenue Henri dunant&postcode=06130`

![Postman sur Grasse](https://user-images.githubusercontent.com/106160198/170036576-31427020-1b55-4e71-bd22-77492cc0b670.png)

Il n'y a aucun résultats retourné, de plus la requête prend plus de 30 sec pour être renvoyée. De plus j'ai testé sur plusieurs villes et adresses dans le 06 et le problème subsiste.

NB: A noter que je n'ai pas testé sur d'autres départements, il est possible que le problème se pose aussi.

**Comment by Mikikou** [comment]
Bonjour, nous sommes également affecté par ce problème

**Comment by mnivel** [comment]
Je suis concerné par le même problème. Les points sont accessibles sur la carte interactive mais l'autocomplétion ne donne pas de résultat pour le 06. Par exemple le point https://adresse.data.gouv.fr/base-adresse-nationale/06004_1130_00010#18.71/43.5797358/7.1242954
10 Rue de Fersen, 06600 Antibes
![antibes_point](https://user-images.githubusercontent.com/14223147/170040034-427c1207-bbe5-4938-8eef-1ec10d582bdb.jpg)
est bien visible mais la recherche ne le trouve pas:
![antibes_autocomplete](https://user-images.githubusercontent.com/14223147/170040111-daf9b2e5-314b-4a1b-a5aa-b170e5d75dd1.jpg)

**Comment by kinamike** [comment]
Il semblerait que le bug soit corrigé, a tester sur les autres département, auquel cas on peut fermer l'issue

**Comment by FrederiqWilliams** [comment]
Bug corrigé
