### ISSUE TITLE
Mettre l'application aux normes d'accessibilité de base

### ISSUE THREAD

**Issue by Maxine-Le-Pennec** [BaseAdresseNationale/adresse.data.gouv.fr#1181]
Il est obligatoire d'ajouter une mention d'accessibilité du site dans le `footer` qu'il soit conforme au non. Il est également nécessaire de se fixer des objectifs de progression.

Afin d'obtenir un site le plus accessible possible et sans l'aide d'un audit, il est nécessaire d'effectuer un diagnostic à notre échelle des soucis d'accessibilité de _adresse.data_ et d'en corriger un maximum.

```[tasklist]
### Urgent
- [x] #1194
```

```[tasklist]
### Tâches d'accessibilité
- [x] #1199
- [x]  #1222
- [x] #1200
- [x] #1201
- [x] #1202

```

**Comment by mmortier** [comment]
Report de tickets  dans le ticket suivant : https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1376
