### ISSUE TITLE
Creer Evenement Adresse_Lab#3 sur la page des evenements

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1184]
Les infos : Adresse_Lab#3, jeudi 16 juin de 10h30 à 12h, Titre : Restitution des  ateliers "Identifiant de l'adresse"

    
lien sur la page d'inscription : 
https://www.eventbrite.fr/e/billets-adresse-lab3-restitution-des-ateliers-identifiant-de-ladresse-354423298627

merci

**Comment by vinsag** [comment]
Quelques questions pour compléter l'évènement:
- Cible utilisateurs : utilisateurs techniques ou autre cible ?
- Subtiles : Restitution des ateliers "Identifiant de l'adresse ?  ou un titre plus court
- Description : il faudrait une description pour cet evènement
- Tags pour cet evènement:

**Comment by FrederiqWilliams** [comment]
Cible : Utilisateurs de la BAN
Sub title : Identifiant de l'Adresse
Description  : Restitution des ateliers "Identifiant de l'adresse " qui se sont tenus les 21 Avril et 12 Mai 2022
Tags : Adresse / Adresse_Lab/Technique
