### ISSUE TITLE
Edition de certificat de numérotage à partir de la BAN

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1206]
Fonctionnalité de génération de certificat d'adressage/de numérotage à partir de la BAN. 
Uniquement sur une adresse certifiée, d'une BAL, et avec la parcelle cadastrale remplie --> c'est une compétence Mairie
(Q aspect juridique? )

Possibilité de générer un extrait de la BAN (pdf?) dans un formulaire avec une mention officielle permettant de justifier d'une adresse. équivalent certificat d'adressage. 

Cible : 
- les particuliers qui veulent justifier de l'existence de leur adresse pour la faire modifier auprès d'un organisme
**_En tant que citoyen, j'ai besoin d'un certificat d'adressage pour le transmettre à l'opérateur. Aujourd'hui je le demande à la Mairie, c'est chronophage et demande une charge de travail à un agent. J'aimerai pouvoir le télécharger directement en ligne à partir de l'explorateur._** 
- les notaires qui ont besoin de cette information pour les transactions immobilières
- les mairies pour leur faciliter l'émission d'un certificat d'adressage

Contenu à définir et adhésion des mairies à confirmer. 
- pas de données personnelles, ou à compléter par la mairie
pour exemple voir https://guide-bonnes-pratiques.adresse.data.gouv.fr/information/exemple-de-certificat-dadressage 
- rattachement à l'info de la parcelle cadastrale 

Définir le modèle de formulaire. 
Faut-il un formulaire pour les particuliers et un pour les mairies?

**Comment by FrederiqWilliams** [comment]
il semble qu'il n'y ait pas de "formulaire" administratif existant pour les certificat de numérotage. (ne figure pas dans le code de l'urbanisme. )

ex de formulation possible : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Je soussigné, -------, Maire de la commune de -----, certifie que le bâtiment sis ------– , cadastré section --- n° ---- pour une contenance totale de 7 ------- , porte le N° ----- . voie

En foi de quoi nous délivrons la présente attestation, pour servir et valoir ce que de droit.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Ariane-Rose** [comment]
**Template de certificat d'adressage**

[Logo Marianne]
Commune de [Nom de la commune] 





**Certificat de numérotage**



La commune de [Nom de la commune] atteste que l’adresse certifiée dans sa Base Adresse Locale, associée à la parcelle cadastrale [Parcelle cadastrale] est :

[Parcelle cadastrale]
[Numéro] [Nom de voie] / [Nom de voie en langue régional]
[Lieu-dit] / [Lieu-dit en langue régional]
[Code postal] [Nom de la commune]


[Capture de l’adresse sur l’explorateur]
[Lien vers l’adresse sur l’explorateur]

Pour servir et valoir ce que de droit, le [JJ/MM/AAAA]


L’équipe adresse
[Logo]


_Signaler un problème à la commune de [Nom de la commune]_

**Comment by oonoqi** [comment]
Bonjour,
Merci de travailler sur cette fonctionnalité , qui, je pense aussi, sera utile.

Par rapport à l'exemple dans le guide des bonnes pratiques, il manque le nom et adresse du destinataire du certificat
Je n'ai pas le détail mais je sais que la demande est régulièrement faite à notre secrétaire de mairie .

Bonne journée

**Comment by mmortier** [comment]
[Lien vers l’adresse sur l’explorateur] on peut le mettre mais il faut garder à l'idée qu'on peut avoir une modification de la clef d'interop de l'adresse et donc le lien peut être brisé.

**Comment by mmortier** [comment]
En attente de savoir ce qu'il faut modifier pour pouvoir mettre en production.
La fonctionnalité est prête.

**Comment by FrederiqWilliams** [comment]
Etudier dispositif activable à la commune

**Comment by vinsag** [comment]
Livre en production et cours de recette, je ferme ce ticket
