### ISSUE TITLE
Ajouter le 22 septembre comme événement partenaire de la Charte 

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1208]
{
"title": "Événement Partenaire de la Charte de la Base Adresse Locale",
"description": "Chaque mois, les organismes partenaires de la Charte de la Base Adresse Locale sont invités à échanger sur l'adresse, les évolutions de l'éditeur Mes Adresses, l'accompagnement, la formation, les avancées législatives, etc. L'objectif est de faciliter l'accompagnement des communes et de fluidifier les retours utilisateurs. Inscription automatique après adoption de la charte, contacter [adresse@data.gouv.fr](mailto:adresse@data.gouv.fr)",
"type": "Séminaire",
"target": [
"Communes",
"EPCI",
"Départements",
"IDG",
"entreprises partenaires de la Charte de la Base Adresse Locale"
],
"date": "22-09-2022",
"tags": [
"Programme Base Adresse Locale",
"Base Adresse Locale",
"Base Adresse Nationale",
"Gouvernance"
],
"isOnlyOnline": true,
"adress": {
"name": "",
"numero": "",
"voie": "",
"codePostal": "",
"commune": ""
},
"href": "",
"isSubscriptionClosed": true,
"instructions": "",
"heureDebut": "14:00",
"heureFin": "15:30"
}

**Comment by Maxine-Le-Pennec** [comment]
Ajout mergé
