### ISSUE TITLE
Ajouter la commune Entre-Deux parmi les partenaires de la Charte

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1217]
**Nom :** Entre-Deux (si besoin du code INSEE : 97403)
**Type de charte :** communes
**Localisation :** La Réunion

**Lien :** https://entredeux.re/charte-de-la-base-adresse-locale
**Logo si possible placer les deux logos** 

![Entre-Deux - LOGO +Sign +Cart RVB](https://user-images.githubusercontent.com/69309231/176693936-844e6b75-8008-4981-ac86-64790c84d76f.png)

![Petite Ville Créole de Demain bleu et vert_page-0001](https://user-images.githubusercontent.com/69309231/176693985-40726955-ba52-4bfa-8af2-bb4bdc2bccb5.jpg)

**Comment by Maxine-Le-Pennec** [comment]
Il va me manquer pas mal d'informations Sophie.

- Le code région
- Le code département
- Les services

Pour les logos je peux en mettre qu'un seul, mais je peux essayer de les bricoler pour n'en faire qu'une image :)

**Comment by Maxine-Le-Pennec** [comment]
![entre-deux](https://user-images.githubusercontent.com/66621960/176880462-6935f45b-46af-4c90-af16-7bb4fcecc62e.jpg)
