### ISSUE TITLE
Référencer Adresse en région sur la page des événements

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1226]
Nom : **Adresse en région**
Adresse en région réunit les acteurs de la fabrique de l'adresse en ateliers pour partager sur les problèmes et les bonnes pratiques, en petit format pour élaborer ensemble des solutions concrètes pour faciliter la création et la mise à jour des adresses par les communes. Ces ateliers sont réservés aux acteurs publics. Pour participer à Adresse en région dans votre département ou se porter volontaire pour co-organiser : adresse@data.gouv.fr 

#ProgrammeBaseAdresseLocale #BaseAdresseLocale #BaseAdresseNationale #CoConstruction #Agile

**Dates :** 
* 1er juin à Rennes
* 6 septembre à Landerneau
* 11 octobre à Amiens

**Comment by Ariane-Rose** [comment]
Horaires : 14h - 17h30

Cibles : communes et EPCI

Lieux :
Ti Lab 5 Rue Martenot, 35000 Rennes
Maison de Services Au Public 59, rue de Brest 29800 LANDERNEAU
Somme numérique 43 avenue d'Italie, 80090 Amiens

**Comment by C-Sophie** [comment]
Maxine, si on pouvait préciser les départements concernés pour chaque rencontre, ce serait super.  

- 1er juin à Rennes
Ille-et-Vilaine (35) et Morbihan (56)
Organisé avec GéoBretagne
- 6 septembre à Landerneau
Côtes-d'Armor (22) et Finistère (29) 
Organisé avec GéoBretagne et la Communauté d’Agglomération du Pays de Landerneau-Daoulas
- 11 octobre à Amiens
Aisne (02), Oise (60) et Somme (80)
Organisé avec Somme Numérique (autres en cours)

(On indique les adresses mais ce n'est pas ouvert, il faut s'inscrire)

Et s'il y a de la place ce serait bien d'indiquer les partenaires qui organisent avec nous 
(je les ai mis en dessous des départements concernés : liste pas complète pour le 3e à Amiens)
