### ISSUE TITLE
Mettre à disposition les exports communaux dans la page données nationales

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1254]
objectif : rassembler les données en téléchargement dans une même page. 
Documenter les différents exports

**Comment by mmortier** [comment]
Les exports communaux sont disponibles sur la page commune par exemple : https://adresse.data.gouv.fr/commune/94067
faut-il rajouter une barre de recherche sur le code insee pour accéder directement au téléchargement de la BAL?

**Comment by mmortier** [comment]
@FrederiqWilliams ? Est-ce que le besoin existe toujours?

**Comment by FrederiqWilliams** [comment]
les exports communaux restent sur la page commune. 
Refléchir à proposer les exports BAN sur l'emprise communale
