### ISSUE TITLE
Ajouter la date du 25 octobre dans les événements partenaires de la Charte

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1259]
{
"title": "Événement Partenaire de la Charte de la Base Adresse Locale",
"description": "Chaque mois, les organismes partenaires de la Charte de la Base Adresse Locale sont invités à échanger sur l'adresse, les évolutions de l'éditeur Mes Adresses, l'accompagnement, la formation, les avancées législatives, etc. L'objectif est de faciliter l'accompagnement des communes et de fluidifier les retours utilisateurs. Inscription automatique après adoption de la charte, contacter [adresse@data.gouv.fr](mailto:adresse@data.gouv.fr)",
"type": "Séminaire",
"target": [
"Communes",
"EPCI",
"Départements",
"IDG",
"entreprises partenaires de la Charte de la Base Adresse Locale"
],
"date": "25-10-2022",
"tags": [
"Programme Base Adresse Locale",
"Base Adresse Locale",
"Base Adresse Nationale",
"Gouvernance"
],
"isOnlyOnline": true,
"adress": {
"name": "",
"numero": "",
"voie": "",
"codePostal": "",
"commune": ""
},
"href": "",
"isSubscriptionClosed": true,
"instructions": "",
"heureDebut": "14:00",
"heureFin": "15:30"
}

**Comment by Maxine-Le-Pennec** [comment]
Sophie, je me permets de te donner le modèle à jour que l'on utilise pour les événements :)


```
  {
    "title": "Événement Partenaire de la Charte de la Base Adresse Locale",
    "description": "Chaque mois, les organismes partenaires de la Charte de la Base Adresse Locale sont invités à échanger sur l'adresse, les évolutions de l'éditeur Mes Adresses, l'accompagnement, la formation, les avancées législatives, etc. L'objectif est de faciliter l'accompagnement des communes et de fluidifier les retours utilisateurs. Inscription automatique après adoption de la charte, contacter adresse@data.gouv.fr",
    "type": "partenaire",
    "target": "Communes, EPCI, départements, IDG et entreprises partenaires de la Charte de la Base Adresse Locale ",
    "date": "2022-10-25",
    "tags": [
      "Programme Base Adresse Locale",
      "Base Adresse Locale",
      "Base Adresse Nationale",
      "Gouvernance"
    ],
    "isOnlineOnly": true,
    "address": {
      "nom": "",
      "numero": "",
      "voie": "",
      "codePostal": ""
    },
    "href": "",
    "isSubscriptionClosed": true,
    "instructions": "",
    "startHour": "14:00",
    "endHour": "15:30"
  }
```
