### ISSUE TITLE
Les variables d'environnement ne semblent pas être récupérées

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#1285]
On ne résout qu'une partie de problème ici. La nouvelle URL est ok, mais la variable d'env reçu est toujours vide et nous utilisons donc toujours la fallback.

_Originally posted by @tmerlier in https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1282#issuecomment-1231387881_

**Comment by Maxine-Le-Pennec** [comment]
Si je logue `process.env.NEXT_PUBLIC_API_ETABLISSEMENTS_PUBLIC`, je récupère bien `https://plateforme.adresse.data.gouv.fr/api-annuaire/v3`
