### ISSUE TITLE
Ajout de date Evenement partenaire

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1319]
{
    "title": "Événement Partenaire de la Charte de la Base Adresse Locale",
    "description": "Chaque mois, les organismes partenaires de la Charte de la Base Adresse Locale sont invités à échanger sur l'adresse, les évolutions de l'éditeur Mes Adresses, l'accompagnement, la formation, les avancées législatives, etc. L'objectif est de faciliter l'accompagnement des communes et de fluidifier les retours utilisateurs. Inscription automatique après adoption de la charte, contacter adresse@data.gouv.fr",
    "type": "partenaire",
    "target": "Communes, EPCI, départements, IDG et entreprises partenaires de la Charte de la Base Adresse Locale ",
    "date": "2022-12-08",
    "tags": [
      "Programme Base Adresse Locale",
      "Base Adresse Locale",
      "Base Adresse Nationale",
      "Gouvernance"
    ],
    "isOnlineOnly": true,
    "address": {
      "nom": "",
      "numero": "",
      "voie": "",
      "codePostal": ""
    },
    "href": "",
    "isSubscriptionClosed": true,
    "instructions": "",
    "startHour": "14:00",
    "endHour": "15:30"
  }

**Comment by vinsag** [comment]
@C-Sophie : L'inscription est elle déja close pour cet évènement  car nous avons isSubscriptionCloses à true ?
Il manque la ligne instructions non avec le texte : Inscription automatique après adoption de la charte, contacter adresse@data.gouv.fr

Est ce que c'est normal suite à mes remarques ou dois je faire les changements pour mettre false et ajouter une instruction comme les autres évènements du même type ?

**Comment by C-Sophie** [comment]
L'inscription est close car les partenaires de la charte ne s'inscrivent pas. Ils sont d'office tous invités. Il n'y a pas d'inscription possible pour des extérieurs.
