### ISSUE TITLE
Problème d'affichage des positions d'un numéro au chargement de la page

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#1328]
## Contexte
Lorsque l'on charge directement la page d'un numéro sur la carte BAN, seulement une position s'affiche sur la carte même si le menu en indique bien plusieurs.

Exemple : 33 Rue des Moulins - Verberie (60667) 
https://adresse.data.gouv.fr/base-adresse-nationale/60667_0280_00033#18.61/49.31465/2.7411

Par ailleurs, si on ouvre le numéro en le sélectionnant depuis la voie, toutes les positions s'affichent correctement.

### En chargeant la page
![Capture d’écran 2022-10-21 à 09 42 14](https://user-images.githubusercontent.com/7040549/197141314-d5908fe4-b6b3-431c-b859-de65452dac4d.png)

### En sélectionnant depuis la voie
![Capture d’écran 2022-10-21 à 09 42 42](https://user-images.githubusercontent.com/7040549/197141380-a67d5ba6-b27b-4614-b163-0036c7785ed1.png)

**Comment by GllmR** [comment]
Les positions sont bien affichées, c'est le zoom qui se fait sur la position principale au lieu de se centrer sur toutes les positions.

**Comment by IGNFBourcier** [comment]
## Recap
l'accés au [numero via une url sans hash](https://adresse.data.gouv.fr/base-adresse-nationale/60667_0280_00033) est cadré sur
 - le `displayBBox`, qui correspond pour le moment à la position principale
 - ou si il y a plusieurs positions, sur l'étendu de l'ensemble des points

l'accés au [numero via une url avec hash](https://adresse.data.gouv.fr/base-adresse-nationale/60667_0280_00033#18.61/49.31465/2.7411) est cadré suivant les parametres du hash (zoom , centre ...).
Le ou les positions du numéros peuvent etre hors du cadrage.

IMHO: Pas d'erreur de comportement. L'url permet d'acceder à la fiche du numero, et le hash de definir un cadrage.
Si un hash est présent, il serai dommage de forcer automatiquement le cadrage sur les elements et 'casser le hash'.

Il reste un souci  visibilité-position-identification des differentes positions par l'utilisateur sur la carte.

## Amélioration
Pour ameliorer l'experience utilisateur, on pourrai proposer un mecanisme de mis en evidence ou recentrage sur la position à sa demande (exemple clic sur le carré batiments rouge dans fiche)

**Comment by mmortier** [comment]
fixed
