### ISSUE TITLE
Page de présentation des réutilisateurs de la BAN

### ISSUE THREAD

**Issue by olivierdelteil** [BaseAdresseNationale/adresse.data.gouv.fr#1336]
Créer une page dédiée à la présentation des réutilisateurs de la BAN : 
- dans un premier temps affichage des logos des réutilisateurs (à fournir par Olivier semaine 45 dans un dépot ultérieur sous forme de .zip)
- dans un second temps, présentation des liens vers les témoignages si présents dans le blog

Cette page est rubriquée "Données Nationales" et aura pour titre : "Qui réutilise la BAN ?"
Sous le titre seront disposés les logos des réutilisateurs à la manière de ce qu'a réalisé transport.data.gouv sur sa page d'acceuil.
Sous les logos sera ajoutée la mention : "vous êtes utilisateur de la BAN et souhaitez apparaitre sur cette page ? cliquez ici (lien = [adresse@data.gouv.fr](mailto:adresse@data.gouv.fr).)

Ajouter sur la page d'accueil adresse.data.gouv.fr le bouton d'accés à cette page "réutilisateurs" au coté du bouton "Découvrir la BAN et accéder aux données" et l'intituler "Voir qui réutilise la BAN

les logos sont disponibles ici : https://drive.google.com/drive/folders/1wi41vfLVvX0lMF89vZxGui_ILx9UV2Ay?usp=sharing

**Comment by olivierdelteil** [comment]
J'ai ajouté qqs logos de réutilisateurs
peut être ajouter sous le titre "Qui réutilise la BAN ?" une mention en corps-1 "Quelques exemples parmi les milliers d'usages périodiques de la BAN"

**Comment by olivierdelteil** [comment]
Textes de description des usages : 
DOUANES : 
"Géocodage dans plusieurs applications"
INSTANT SYSTEM : 
"intégré dans les solutions de mobilité"
MIN EDUC NAT : 
"usage sur 2 applications MENS en délégation de service"
POSTCODE.EU
"integrated into an international adress API"
GENDARMERIE Nationale :
"usage du géocodeur"
HERE TECHNOLOGIES :
"Alimentation du référentiel en données adresse"
IGN : 
"Alimentation du référentiel en données adresse"
TOMTOM : 
"Alimentation du référentiel en données adresse"
ACCESLIBRE :
"Enrichissement du formulaire de description des ERP"
SDIS64 :
"Enrichissement du référentiel d'intervention"

**Comment by olivierdelteil** [comment]
Comment je peux voir les modifications effectuées ?

**Comment by FrederiqWilliams** [comment]
Discussion réutilisateurs vs utilisateurs vs usagers; Parler plutôt d'usagers puisque c'est une service public. Rajouter la typologie des usages. 


Modifier le titre de la page en "Les usages de la BAN"

**Comment by mmortier** [comment]
Frédérique peux-tu faire un nouveau ticket. celui-ci est clos.
