### ISSUE TITLE
Ajout du formulaire d'inscription à l'outil d'animation du collectif des usagers

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1342]
Besoin : mettre sur le site adresse l'accès à la plateforme osmose d'animation du collectif des usagers. 
Passe par un formulaire d'inscription, code ci-dessous. 

code pour inserer le formulaire d'inscription. 

<iframe src="https://analytics-eu.clickdimensions.com/ignfr-agj1s/pages/pat1ve7fee27owanot90mw.html?PageId=bcf5a4a5c54eed11bba3000d3adf7433" allowtransparency="true" width="100%" height="500px" type="text/html" frameborder="0" style="border:0"></iframe>

Proposition: mettre le bouton d'accès au formulaire sur la page https://adresse.data.gouv.fr/contribuer

En bas dans l'espace "En tant qu’utilisateur des données"

Rajouter : 
"Vous souhaitez participer aux échanges et à la co-construction des évolutions de la BAN ou services associé, alors rejoignez nous dans la démarche Adresse_Lab."

avec un bouton "Pour nous rejoindre" qui pointe sur le formulaire d'inscription

**Comment by mmortier** [comment]
@Ariane-Rose  et @FrederiqWilliams l'information a été remontée à l'IGN mais il ne semble pas y avoir de changement.
On fait quoi? On passe la PR où on annule la demande et je clos le ticket?

**Comment by FrederiqWilliams** [comment]
Pour le formulaire : remplacer le formulaire initialement prévu par un formulaire Cryptad, même contenu

**Comment by mmortier** [comment]
La solution CryptPad impose d'aller voir les résultats régulièrement dans CryptPad. Il s'agirait encore d'un outil supplémentaire.

La demande est modifiée : 

dans la section utilisateurs de https://adresse.data.gouv.fr/contribuer
modifier le paragraphe  : 


![Image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/7045982/fac9f082-9bd1-4c54-8fe5-5128ea3e7354)

Texte :  
(A mettre avant le paragraphe sans remplacer)
"Utilisateurs : rejoignez notre collectif des usagers de la BAN. Demandez par mail à rejoindre le _METCT-collectif-des-utilisateurs-de-la-ban_ en envoyant une demande sur adresse@data.gouv.fr"
Bouton (lien : https://osmose.numerique.gouv.fr/)
Texte du bouton : "Rejoignez nous sur OSMOSE"

**Comment by mmortier** [comment]
@FrederiqWilliams petite question tu préfères qu'on mette les deux phrase en suivant et les boutons cote cote? Ou une phrase le bouton puis une phrase le bouton? Je sais pas si c'est clair..
