### ISSUE TITLE
Mise à jour du blog et du peertube

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/adresse.data.gouv.fr#1359]
Pour mettre à jour le blog la documentation se trouve ici : 
https://github.com/BaseAdresseNationale/infra/blob/master/docs/install_ghost.md
Pour mettre à jour le peertube la documentation ici : 
https://docs.joinpeertube.org/install-any-os?id=upgrade

**Comment by tmerlier** [comment]
Peertube vient d'être mis à jour en `v.4.3.1` et Ghost en `v.4.48.9`
