### ISSUE TITLE
organisation des resultats de l'autocompletion sur l'adresse pertubante

### ISSUE THREAD

**Issue by IGNFBourcier** [BaseAdresseNationale/adresse.data.gouv.fr#1362]
Sur une recherche de commune, ou adresse incomplete sur https://adresse.data.gouv.fr/ ou https://adresse.data.gouv.fr/base-adresse-nationale l'autocompletion propose des résultats triés par pertinance avec une présentation par "catégories" (rue, communes, lieux dit)
Hors si les catégories se croisent elle ne sont pas réécrites : on peut retrouver dans la deuxième catégorie des elements de la première

exemple
![image](https://user-images.githubusercontent.com/62593305/205125921-86851b53-9791-40d2-bce0-cae5fe46d9ea.png)

Le premier resultat est une rue, le deuxieme est une commune, les suivant sont certainement des rues.

autre exemple:
![image](https://user-images.githubusercontent.com/62593305/205126883-0b5d6140-a079-48e1-9099-cd0203db5cd3.png)

**Comment by mmortier** [comment]
Je pense qu'il faudrait prendre un parti pris.
On doit privilégier la pertinence sans perdre l'info de la catégorie.
Je propose de changer l'affichage en fonction de la catégorie : 
lieu dit, rue et commune : 
![image](https://user-images.githubusercontent.com/7045982/226863695-1a1b17d1-3e66-4f2c-af4a-9b9e12104418.png)
![image](https://user-images.githubusercontent.com/7045982/226863793-9b35192f-86a2-4353-8c6a-05a0854d7d50.png)
![image](https://user-images.githubusercontent.com/7045982/226863867-510b45e9-9ca8-4063-b80f-963e0faa5e1c.png)
@FrederiqWilliams et @Ariane-Rose

**Comment by mmortier** [comment]
autre possibilité on met un picto devant le résultat.
encore une autre on met (rue), (lieu-dit) ou (commune) derrière le résultat.

**Comment by FrederiqWilliams** [comment]
Ce n'est pas la visualisation du résultat qui pose souci, pas besoin de modifier, garder la catégorisation en bandeau comme dans le menu déroulant actuel. 
Par contre veiller à ce que les résultats retournés se trouvent classés dans la bonne catégorie
