### ISSUE TITLE
Ajout d'une page de présentation d'indicateurs d'impact

### ISSUE THREAD

**Issue by olivierdelteil** [BaseAdresseNationale/adresse.data.gouv.fr#1368]
Création d'une page de présentation d'indicateurs d'impact des usages la BAN.

L'accès à cette page s'effectue depuis le pied de page du site sous "mentions légales" avec l'intitulé "Indicateurs d'impact"
(rien n'empêche ultérieurement de pointer sur cette page depuis des zones du site)

Un modèle de présentation peut être pris sur la page Beta qui traite du sujet :
https://beta.gouv.fr/stats/

Autoformation : Le détail du paramétrage des données peut être consulté sur la video suivante : (https://peertube.adresse.data.gouv.fr/w/tjtKpmFv2MrSo5vHUAkBaJ))

```[tasklist]
### Organisation & Documentation
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1446
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1379
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1456
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1455
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1573
```

**Comment by mmortier** [comment]
Une page de statistiques d'utilisation de la BAN a été créée.
Elle sera améliorée dans une V2.
