### ISSUE TITLE
Actualisation du schema d'alimentation de la BAN sur  la Page Données Nationales

### ISSUE THREAD

**Issue by olivierdelteil** [BaseAdresseNationale/adresse.data.gouv.fr#1370]
Actualisation du Schéma 
https://drive.google.com/file/d/1Un7luw3KgfhaJ_OC83jlYloAdix7r1Dj/view?usp=share_link

sur la page 
https://adresse.data.gouv.fr/donnees-nationales

**Comment by jdesboeufs** [comment]
L'immense majorité des données viennent de l'IGN lorsque la commune n'a pas de BAL. Pourquoi faire disparaître cette information du schéma ?

**Comment by mmortier** [comment]
Oui c'est vrai. Je clos le ticket. On laisse les données d'origines.
