### ISSUE TITLE
Gestion des communes déléguées (et autres communes anciennes)

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1373]
Issue en lien avec https://github.com/BaseAdresseNationale/ban-plateforme/issues/127

Nous recevons sur le support le signalement provenant de Dunkerque qui veut savoir comment gérer "Saint-Pol-sur-Mer", commune associée à Dunkerque. 
Aujourd'hui le champ commune déléguée est prévu par le format BAL (`commune_deleguee_insee` et `commune_deleguee_nom`) mais pas restitué par la BAN. 

- **Exemple de gestion (adresses composites de Dunkerque dans la BAN)**

<img width="395" alt="Capture d’écran 2022-12-13 à 11 20 50" src="https://user-images.githubusercontent.com/69309231/207291964-a8900baf-9ed5-4996-a2f4-bcc424e52021.png">
BAN : https://adresse.data.gouv.fr/base-adresse-nationale/59183#11.77/51.017/2.3435
Ajout de St Pol dans le nom des voies situées sur l'ancienne commune de Saint Pol.

- D'autres communes ajoutent les noms des anciennes communes dans le champ `lieudit_complement_nom`: problématique car les communes déléguées et les lieux-dits sont gérés de la même manière [exemple de Bréau-et-Mars](https://adresse.data.gouv.fr/base-adresse-nationale/30052_8y9vjj#17.81/44.0005/3.55685) 
- D'autres communes ajoutent le nom de l'ancienne commune entre parenthèses dans le nom de la voie

**Comment by mmortier** [comment]
Normalement avec la correction qui a été faite sur le ticket https://github.com/BaseAdresseNationale/ban-plateforme/issues/127 je pense que si la code commune déléguée et nom commune délégué est bien remplit, nous allons retrouver les codes fantoirs des anciennes communes, les voies ne fusionneront que si le code fantoir est le même.

Il ne faut pas mettre le nom de l'ancienne commune avec un tiret dans le libellé de la voie car nous allons perdre la correspondance entre le libellé et le fantoir de l'ancienne commune.

@C-Sophie tu peux voir avec eux pour faire une BAL avec ces consignes?

**Comment by C-Sophie** [comment]
Même problème @mmortier avec des libellés comprenant un tiret suivi du nom de l'ancienne commune. 
Le mailing est prévu.

**Comment by mmortier** [comment]
A priori si la commune enlève du nom de la voie le nom de l'ancienne commune les voies devraient fusionner.
La commune n'a pas modifié sa BAL sur les voies citées plus haut.
Si elle le fait les voies vont fusionner.
Je clos le ticket.
