### ISSUE TITLE
statistiques d'utilisation de la BAN

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1375]
regroupe plusieurs tickets permettant d'obtenir des statistiques d'utilisation/téléchargement de la BAN
- [ ] ticket https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1368 
- [ ] ticket : https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1379

**Comment by nkokla** [comment]
- [ ] #1380 
- [ ] #1379
