### ISSUE TITLE
ajouter un compteur de téléchargement des données BAN

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1379]
Dans le but de créer des indicateurs de l'utilisation de la BAN, voir comment créer un compteur de téléchargement de la BAN et comment l'exposer sur la page des utilisateurs?
Par exemple savoir combien de fois a été téléchargé la BAN sur le mois.

**Comment by olivierdelteil** [comment]
Au-delà du nombre de téléchargement global, l'idéal serait de présenter via un graph, les chargements par typologie de données en csv(x département, y addok, z format BAL, u cadastre, ...)

**Comment by olivierdelteil** [comment]
Des indicateurs issus des données extraites de l'usages des fichiers BAN téléchargés (si on peut l'obtenir) portant notamment :

la source de téléchargement (eg le réutilisateur)
la nature des données traitées (n°, nom voie, commune ?)
volumétrie de données (approx) téléchargées
fréquence de téléchargement
la catégorie d'utilisateur
Les formats de visualisation restent à définir en fonction de la typologie de données exposées.

Un modèle de présentation peut être pris sur la page Beta qui traite du sujet :
https://beta.gouv.fr/stats/

**Comment by mmortier** [comment]
On voudrait connaitre le nombre de téléchargements de tous les dossiers et sous dossiers de https://adresse.data.gouv.fr/data/ban/adresses/latest/

Dans un premier temps une liste par dossiers avec le nom du fichier et le nombre de téléchargements.
On doit intercepter l'action du téléchargement pour récupérer l'info qu'il y a un téléchargement.

voir comment on stocke l'info? On enregistre chaque jour, puis en fait les regroupements ensuite.

**Comment by mmortier** [comment]
Piste sur matomo on pourrait paramétrer un indicateur de téléchargement ? https://stats.data.gouv.fr/index.php?module=API&action=listAllAPI&idSite=13&period=range&date=previous30#/Actions

- Actions.getDownloads (idSite, period, date, segment = '', expanded = '', idSubtable = '', flat = '') [ Example in [XML](https://stats.data.gouv.fr/index.php?module=API&method=Actions.getDownloads&idSite=13&period=range&date=previous30&format=xml&token_auth=anonymous), [Json](https://stats.data.gouv.fr/index.php?module=API&method=Actions.getDownloads&idSite=13&period=range&date=previous30&format=JSON&token_auth=anonymous), [Tsv (Excel)](https://stats.data.gouv.fr/index.php?module=API&method=Actions.getDownloads&idSite=13&period=range&date=previous30&format=Tsv&token_auth=anonymous&translateColumnNames=1) , RSS of the last [10 days](https://stats.data.gouv.fr/index.php?module=API&method=Actions.getDownloads&idSite=13&period=day&date=last10&format=rss&token_auth=anonymous&translateColumnNames=1) ]
- Actions.getDownload (downloadUrl, idSite, period, date, segment = '') [ No example available ]

**Comment by mmortier** [comment]
On attend d'avoir le nouveau matomo pour créer un compteur de clic sur les téléchargements

**Comment by mmortier** [comment]
On attend l'accès au nouveau matomo

**Comment by olivierdelteil** [comment]
Data.gouv m'informe que la version actuelle de Matomo peut rester sur l'environnement Data et non Beta.
Donc on reste sur la même instance. 
Besoin de lister les fonctionnalités Matomo dont nous avons besoin, au-delà du tracking des downlaods ? besoin d'une PR spécifique ?
