### ISSUE TITLE
Source IGN remplacée par source Inconnue dans l'export de la BAN

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1385]
**La source IGN est bien présente dans l'explorateur de la BAN :** 
<img width="506" alt="Capture d’écran 2022-12-27 à 12 18 15" src="https://user-images.githubusercontent.com/69309231/209659218-2a903026-44b8-4e71-a5bd-208731cf8f03.png">

**Mais pas dans le fichier BAN en sortie (format BAL 1.3, mais c'est pareil dans le format historique) :** 
<img width="420" alt="Capture d’écran 2022-12-27 à 12 18 34" src="https://user-images.githubusercontent.com/69309231/209659260-30b32c52-c17b-4b21-99f1-85d806d62b82.png">

La source Guichet adresse est remplacée par "commune". 

Anomalie détectée en effectuant des captures d'écran pour le Guide des bonnes pratiques de l'adresse. 
Nous conseillons aux communes de vérifier les adresses dans la BAN. Cette action est problématique sur le fichier (mauvaise image d'une adresse "inconnue" par rapport à "IGN").  

**Test sur la commune de Mallemort :**
Explorateur : https://adresse.data.gouv.fr/base-adresse-nationale/13053_xdp80a_00021#18.85/43.73385/5.1807
Fichier BAN au format BAL 1.3 en pj (c'est pareil dans l'export au format historique)
[adresses-13053.csv](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/files/10307798/adresses-13053.csv)

**Comment by mmortier** [comment]
Le mapping des sources actuel est le suivant : 
  * bal: 'commune',
  * 'ign-api-gestion-municipal_administration': 'commune',
  * 'ign-api-gestion-laposte': 'laposte',
  * 'ign-api-gestion-sdis': 'sdis',
  * 'ign-api-gestion-ign': 'inconnue',
  * cadastre: 'cadastre',
  * ftth: 'arcep',
  * 'insee-ril': 'insee'
-> ce qui vient du guichet adresse sort en source "commune"
-> ce qui vient de l'IGN sort en "inconnue".

Cela avait été décidé car les données IGN était une agglomération de données de différentes sources.
De ce que je comprends ce n'est pas un bug.
Je clos le ticket.
