### ISSUE TITLE
Ajout de l'Agglomération Montargoise aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1409]
## Nouveau partenaire

- Nom : Agglomération Montargoise
- Description : L’Agglomération Montargoise propose un accompagnement méthodologique et technique aux communes de son territoire pour la création et la mise à jour de leur Base Adresse Locale. Cet engagement prend la forme d’une collaboration entre le service SIG de l’intercommunalité, les élus et techniciens des communes.
- Lien vers le site : 
- Lien vers la charte : https://geoloiret.loiret-numerique.fr/arcgis/apps/sites/#/agglomontargoise/pages/ame-pluihd
- Date de signature de la charte : 6/12/2022
- Périmètre : les 15 communes de l’Agglomération Montargoise
- Liste des codes département : 45
- Échelon : 1
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Formation", "Accompagnement technique", "Mise à disposition d'outil mutualisé".

Ajouter ici le logo du partenaire
![Logo AME](https://user-images.githubusercontent.com/69309231/213446061-b0d0b889-52dc-4d3d-9c2a-c1d6aa97e08e.jpg)

**Comment by tmerlier** [comment]
Corrigé par #1419
