### ISSUE TITLE
Ajout du SIEL-TE aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1411]
## Nouveau partenaire

- Nom : SIEL-TE
- Description : Le SIEL-TE propose un outil pour accompagner votre commune dans la fiabilisation de l'adressage de votre territoire. Celui-ci vous permettra de diagnostiquer la qualité des adresses de votre commune et vous aidera à résoudre les anomalies d’adressage (modification, doublon, suppression, numérotation des voies…). En complément, il vous permettra également de créer de nouvelles adresses, notamment en lien avec les nouvelles constructions sur votre territoire.
- Lien vers le site : https://www.te42.fr/nos-metiers/information-geographique/
- Lien vers la charte : https://www.te42.fr/wp-content/uploads/2022/08/Charte-de-la-Base-Adresse-Locale-organisme-public.pdf
- Date de signature de la charte : 20/12/2022
- Périmètre : Communes du département de la Loire (42)
- Liste des codes département : 42 (Loire)
- Échelon : 2
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Formation", "Accompagnement technique", "Réalisation des Bases Adresse Locales", "Mise à disposition d'outil mutualisé".

Ajouter ici le logo du partenaire
![logo-siel](https://user-images.githubusercontent.com/69309231/213480905-43c8077f-5dca-46f5-95e9-75f53740eff7.jpg)

**Comment by tmerlier** [comment]
Corrigé par #1419
