### ISSUE TITLE
améliorer la distinction entre les sources (couleurs) d'adresse sur l'explorateur

### ISSUE THREAD

**Issue by Ariane-Rose** [BaseAdresseNationale/adresse.data.gouv.fr#1415]
Les couleurs des points adresse par source sont très proches pour certaines. Pourrait-on améliorer la lisibilité ? 
Notamment : Cadastre et Opérateur THD.

![image](https://user-images.githubusercontent.com/1406032/214593257-6259ff4d-31f3-4cec-9d55-66136caf26f5.png)

**Comment by mmortier** [comment]
Quelles couleurs trouves-tu qui sont trop proches?
Tu peux proposer une nouvelle légende?

**Comment by Ariane-Rose** [comment]
Les couleurs foncées sont trop proches et en particulier cadastre et opérateur.
Sur les choix de couleurs, pas de préférence. Il me semble qu'un orange, rose, bleu clair ... sont des couleurs dispos et qui tranchent bien.

**Comment by FrederiqWilliams** [comment]
La Poste, INSEE et SDIS ne devraient plus être dans les sources.

**Comment by mmortier** [comment]
On a encore des données typées SDIS "ign-api-gestion-sdis" dans les données BAN. On garde.
Par contre on n'a aucune donnée typée INSEE. On peut l'enlever de la légende et du code.

**Comment by mmortier** [comment]
Regrouper les sources IGN/La Poste/SDIS.

**Comment by vinsag** [comment]
Faire une requete pour comptabiliser les différentes sources.
Refaire la liste et attribuer le code couleur

**Comment by vinsag** [comment]
On ferme le ticket pour ouvrir un nouveau ticket pour faire un état des lieux des sources dans la BAN.
