### ISSUE TITLE
Ajout de Lamballe Terre et Mer aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1417]
## Nouveau partenaire

- Nom : Lamballe Terre & Mer
- Description : Le service SIG de Lamballe Terre & Mer se propose, dans le cadre de ses prestations aux Communes, de les accompagner dans la mise en place de leur adressage communal au travers de la Base Adresse Locale. Le service SIG propose un outils de mise à jour et de suivi de l'adressage dans les communes
- Lien vers le site : 
- Lien vers la charte : https://sig.lamballe-terre-mer.bzh/
- Date de signature de la charte : 25/01/2023
- Périmètre : communes de la communauté d'agglomération
- Liste des codes département : 22 (Côtes-d'Armor)
- Échelon : 1
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Formation", "Accompagnement technique", "Réalisation des Bases Adresse Locales", "Mise à disposition d'outil mutualisé".

Ajouter ici le logo du partenaire
![logo-ltm](https://user-images.githubusercontent.com/69309231/214811689-11145f3c-66a7-4008-9a74-083b53ea4444.png)

**Comment by tmerlier** [comment]
Corrigé par #1419
