### ISSUE TITLE
Amélioration de l'affichage des Lieux-dits dans l'explorateur BAN

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1439]
"En tant qu'utilisateur de l'explorateur, je souhaite que l'information des Lieux-Dits soit mise en valeur. 
En effet, les Lieux Dits sont une part importante de l'adresse et après avoir fait l'effort de les compléter il faut les valoriser. 

```[tasklist]
### Tasks
- [x] Grossir la taille de caractère
- [ ] https://github.com/BaseAdresseNationale/ban-plateforme/issues/82
```

https://storage.gra.cloud.ovh.net/v1/AUTH_0f20d409cb2a4c9786c769e2edec0e06/imagespadincubateurnet/uploads/upload_4a734c1f8fddd89f8e15044e2155adb1.png

(Ariane fait une carte)

**Comment by mmortier** [comment]
Pour la police de caractère OK. 

Par contre question, quand on parle de "numéros associés à un lieu dit" on parle du fait 
 qu'il y ait une ligne toponyme en 99999 dans la BAL 
+ un numéro avec nom de voie + un lieu_dit_complement_nom = au toponyme? 

Mais un numéro est associé à une voie et pas à un lieu_dit_complement_nom tout seul non?

**Comment by mmortier** [comment]
vu avec Théophile : 
![Capture d’écran 2023-02-17 à 14 16 18](https://user-images.githubusercontent.com/7045982/219663145-a92ab88c-0fd3-4971-a8bc-6a54c37e09de.png)

**Comment by mmortier** [comment]
On voit déjà les adresses associées au lieu dit au survol mais on ne retrouve pas les numéros associés dans la liste et lorsqu'il y a plusieurs voies avec le même lieu dit comme la haute folie sur Breux sur Avre.

**Comment by mmortier** [comment]
Première PR sur la taille des lieux-dit en production https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1444

**Comment by mmortier** [comment]
résolu
