### ISSUE TITLE
Intégration DSFR

### ISSUE THREAD

**Issue by nkokla** [BaseAdresseNationale/adresse.data.gouv.fr#1441]
Effectuer une première integration du DSFR. 
Le but de cette tache étant uniquement d'intégrer les Header et Footer du DSFR.

```[tasklist]
### Tasks
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1430
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1431
```

**Comment by Ariane-Rose** [comment]
Quelques modifs : 
- Contribuer -> Gérer mes adresses
- dans le menu "Communes et collectivités" : je changerai bien l'ordre

1. Comment mettre à jour mes adresses
2. Outil national Mes Adresses
3. Ressources autour de l'adressage
4. Evènements autour de l'adressage (sans les pour uniformiser)

- dans le menu "Partenaires" : on peut mettre Organismes partenaires à la place ? J'enlèverais le formulaire de dépôt

1. Charte de la Base Adresse Locale
2. Comment mettre à jour les adresses
3. Outil national Mes Adresses
4. Ressources autour de l'adressage
5. Evènements autour de l'adressage
