### ISSUE TITLE
Ajouter une échelle sur l'explorateur de la BAN

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1442]
Pour compléter une demande de subventions, la Ville de Lyon renvoie à la BAN (doc en pj) et demande un plan de situation à l'échelle 1:2000 idéalement. Or l'explorateur de la BAN ne propose pas d'échelle, ce qui rend compliqué le montage du dossier et a généré du support. 

![image](https://user-images.githubusercontent.com/69309231/221156712-f4782d52-bcae-4f49-a696-8b046cbe1089.png)

Proposition : ajouter une échelle sur l'explorateur de la BAN. 
[FICHE-Constitution dossier déclaratio préalable - Ravalement façades.pdf](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/files/10823164/FICHE-Constitution.dossier.declaratio.prealable.-.Ravalement.facades.pdf)

**Comment by nkokla** [comment]
Duplicate of #1437

**Comment by nkokla** [comment]
On va essayer de planifier cette demande rapidement.
