### ISSUE TITLE
problème auto-complétion sur rue de muriers à Virazeil

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1465]
cf ticket de support https://etalab-support.zammad.com/#ticket/zoom/50027
Elle existe dans la BAN  [Rue des Mûriers, Virazeil (47326) - Base Adresse Nationale | adresse.data.gouv.fr](https://adresse.data.gouv.fr/base-adresse-nationale/47326_0064#16.57/44.5068/0.22035) mais n'est pas proposée par l'auto-complétion.

Voir pourquoi?

**Comment by oussamasse** [comment]
Bonjour,
L'auto-complete ne remonte aucune adresse de la commune de Trappes, code postal  78190, insee 78621, pourriez vous créer un issue s'il vous plaît ? Merci
