### ISSUE TITLE
Documentation limite requêtes par seconde

### ISSUE THREAD

**Issue by AntoineAugusti** [BaseAdresseNationale/adresse.data.gouv.fr#1471]
Bonjour l'équipe adresse,

La documentation [de l'API sur api.gouv.fr](https://api.gouv.fr/les-api/base-adresse-nationale) indique que le quota est de 50 rps / IP, toutefois je n'ai pas retrouvé cette information sur [la page de doc de l'API](https://adresse.data.gouv.fr/api-doc/adresse).

Certains réutilisateurs ne passent pas par api.gouv.fr et ne peuvent donc pas connaitre ce quota en avance.

Est-il possible de l'ajouter ici ?

Merci

**Comment by FrederiqWilliams** [comment]
Ajouter sur la page de la doc de l'api un pointer sur la page de documentation de l'API api.gouv.fr. 
Proposition : sous la forme d'un bouton "Documentation de l'API" à positionner dans le bandeau bleu.

**Comment by mmortier** [comment]
C'est ici https://adresse.data.gouv.fr/api-doc/adresse la doc de limitation est mise en ligne
