### ISSUE TITLE
Nombre d'enregistrements dans la base de données

### ISSUE THREAD

**Issue by MalcolmTreanor** [BaseAdresseNationale/adresse.data.gouv.fr#1474]
Lorsque j'ouvre le fichier AddressFrance.csv à partir du fichier compressé, il n'y a que 2,3 millions d'enregistrements dans le fichier texte alors que je m'attendais à plus de 20 millions. Est-ce une erreur ou dois-je télécharger tous les fichiers individuels ?

When I open the AddressFrance.csv file from the Zipped  file, there are only 2.3 million records in the text file when I was expecting >20million. Is this an error or do I need to download all of the individual files?

**Comment by mmortier** [comment]
Il s'agissait d'un problème d'export. La situation est revenue à la normale.
Le problème a été identifié et fait l'objet d'un ticket https://github.com/BaseAdresseNationale/ban-plateforme/issues/107
