### ISSUE TITLE
Mise à jour Matomo

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#1489]
## Contexte
Notre Matomo est actuellement hébergé sur stats.data.gouv.fr, hors celui-ci va bientôt être migré vers stats.beta.gouv.fr.

To do
- [ ] Se synchroniser avec Etalab d'un côté et empreinte-digital de l'autre pour migrer les données existantes
- [ ] Ajouter adresse.data.gouv.fr sur stats.beta.gouv.fr
- [ ] Mettre à jour `PIWIK_URL` et `PIWIK_SITE_ID` dans les variables d'environnement (Piwik et l'ancien nom de Matomo, les variables peuvent être renommées à l'occasion)

**Comment by mmortier** [comment]
en lien avec le ticket #1578

**Comment by mmortier** [comment]
https://mattermost.incubateur.net/betagouv/pl/d6off9q9gjf97p345zpze96stw

**Comment by mmortier** [comment]
pas besoin
