### ISSUE TITLE
Ordre des suffixes sur l'explorateur

### ISSUE THREAD

**Issue by Ariane-Rose** [BaseAdresseNationale/adresse.data.gouv.fr#1492]
Le ter devrait être avant le quater (pas par odre alphabétique donc).
![image](https://user-images.githubusercontent.com/1406032/231994672-b15eb9fe-d769-4d9b-9c04-b1e27fcd6758.png)
https://adresse.data.gouv.fr/base-adresse-nationale/28124_0183#14.24/48.75513/1.1286

**Comment by vinsag** [comment]
Comme dans les suffixes on troue beaucoup de valeurs différentes et que nous n'avons pas de champ prédéfini comme bis ter, quarter. A,B,C ou A1, B1. Nous pourrons reprendre ce ticket une fois que nous aurons fait une nettoyage dans les suffixes et que des tests ont été mis en place pour contrôler les valeurs renseignées.

**Comment by vinsag** [comment]
Finalement nous passons les modifications que nous avons fait pour traiter les premiers cas
