### ISSUE TITLE
Visibilité des adresses non certifiées dans la BAN

### ISSUE THREAD

**Issue by I-Thibaud** [BaseAdresseNationale/adresse.data.gouv.fr#1493]
Bonjour,

Plusieurs communes du territoire de l'EPCI créent des numéros pour des parcelles vides ou dans le cadre de terrains potentiellement divisibles. Je leur avais conseillé de ne pas certifier ces adresses tant que l'arrêté de numérotage n'avait pas été pris. 

Cependant, ces adresses sont quand même visibles dans la BAN (en gris). Cela pourrait engendrer des problèmes au niveau politique.

Serait-il possible de créer un autre statut de certification pour les adresses afin de les laisser visible dans la BAL uniquement pour les administrateurs ? De les masquer ou de ne pas les importer dans la BAN ?

Par avance merci,

Thibaud, Pays d'Iroise Communauté

**Comment by FrederiqWilliams** [comment]
La couleur grise indique déjà que la donnée est en cours de validation donc susceptible d'être modifiée. Elle apparait à titre indicatif. Les données certifiées apparaissent en vert.

**Comment by I-Thibaud** [comment]
Bonjour,

Il y a une différence entre une donnée en cours de validation qui peut être incorrecte ou juste non certifiée, d'une adresse en devenir qu'il est important de stocker sans la diffuser.

 Avec le ZAN, on parle de plus en plus de densification, il est important de prévoir des numéros pour la numérotation à venir. Sauf que réserver un numéro est déjà un acte politique qui peut être réalisé lors de la planification, c'est à dire en bien en amont du projet concret sur le terrain.

La BAL doit aussi être un outil de travail pour les communes. Ces dernières doivent pouvoir saisir des adresses non certifiées non diffusables pour sa planification d'adressage. Un seul outil pour l'ensemble de la compétence.
