### ISSUE TITLE
Améliorer les couleurs des puces et l'affichage de la certification sur mobile

### ISSUE THREAD

**Issue by nicolaschuz** [BaseAdresseNationale/adresse.data.gouv.fr#1497]
-	Lors de la consultation de la carte sur un ordinateur, la légende de la certification porte à confusion pour les couleurs de bâti (rouge) et l’entrée (bleu ciel). En effet le rouge du bâtiment et le rouge de « non certifié » sont très proches. De plus les 2 légendes n’étant pas concomitantes, ni uniformisées je pense que les personnes ne voient pas les couleurs des types de positions. Serait-il possible de mettre la légende des types de position au même endroit ? sous forme de puce également comme les points sur la carte ? changer les couleurs ? (voir exemple en image, l'administré pense que son adresse n'est pas certifiée car le bâtiment est en rouge avec la légende à côté qui indique que rouge n'est pas certifié)
![image](https://user-images.githubusercontent.com/105450308/198049220-87c6c9c1-9883-490d-9343-1be34f277e86.png)

-	Lors de la consultation d’une adresse sur un smartphone, de nombreux administrés pensent que leur adresse n’est pas certifiée, car, sans cliquer sur le bouton « Explorer », par défaut, l’info de certification n’apparait pas, et la couleur des puces également porte à confusion (nous avons déjà eu 2 retours similaires à celui-ci, de nombreux usagers utilisent un smartphone pour consulter la base adresse).

**Comment by mmortier** [comment]
Serait corrigé par le ticket https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1415?

**Comment by nicolaschuz** [comment]
> Serait corrigé par le ticket #1415?

Non, car la couleur pour le point "bâtiment" est toujours rouge, comme "non certifiée".
Il faut juste éviter le rouge pour les différents points.

**Comment by vinsag** [comment]
Suite à une refonte du site en cours, nous n'aurons plus du tout la meme page. Je ferme donc cette issue
