### ISSUE TITLE
Gestion des communes fusionnées - Améliorer la mise en visibilité dans l'explorateur BAN

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1501]
Dans l'explorateur BAN,  mettre en visibilité le  contenu du champ "commune ancienne" pour lever les ambiguités.  

L'associer à l'affichage au niveau de la voie, en dessous de la commune actuelle
- avec l'ancien code INSEE (?) ou pas utile?

Au niveau de l'adresse, ce champ "ancienne commune" correspond (souvent/systématiquement?)  au "libellé d'acheminement". Faut-il le remplacer ou considérer que le besoin d'information est rempli?

**Comment by mmortier** [comment]
Pour ce qui est de remplacer le libellé d'acheminement par le nom ancienne commune c'est un autre sujet. Je pense que sur Bordeaux il y a des cas où ils ne sont pas identiques.

**Comment by mmortier** [comment]
Une même voie peut être sur plusieures communes anciennes différentes. 
est-ce que je peux traduire la demande par on veut faire apparaitre dans la fiche de l'adresse à gauche https://adresse.data.gouv.fr/base-adresse-nationale/48009_0083_02367#18.93/44.70935/3.30685


![Image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/7045982/2ac24707-dbc2-46f6-a03c-d62b4935720e)

le nom de la commune ancienne?

**Comment by mmortier** [comment]
Ok pour @FrederiqWilliams
