### ISSUE TITLE
Ajout de Communauté urbaine de Dunkerque aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1503]
## Nouveau partenaire

- Nom : Communauté urbaine de Dunkerque
- Description : Les services de la Communauté urbaine de Dunkerque travaillent avec les communes pour améliorer la base adresse nationale, qui vise à géolocaliser chaque adresse postale sur le territoire français. Cela passe par la création de bases adresse locale, pour lesquels les équipes recensent les créations et modifications de noms de voies, vérifient le placement et la numérotation des bâtiments. Ce travail permet ensuite de faciliter l'accès aux services publics (infrastructures, réseaux…) et aux services localisés (livraisons…).
- Lien vers le site : https://www.communaute-urbaine-dunkerque.fr/les-bases-adresses-de-la-communaute-urbaine-de-dunkerque
- Lien vers la charte : https://www.communaute-urbaine-dunkerque.fr/les-bases-adresses-de-la-communaute-urbaine-de-dunkerque
- Date de signature de la charte : 14/04/2023
- Périmètre : Communauté urbaine de Dunkerque
- Liste des codes département : 59
- Échelon : 1
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Formation", "Accompagnement technique", "Réalisation des Bases Adresse Locales", "Mise à disposition d'outil mutualisé".

Ajouter ici le logo du partenaire
![logo_cud](https://user-images.githubusercontent.com/69309231/234209368-f0959600-41e8-478f-81a2-c20d7d4bdf17.png)

**Comment by vinsag** [comment]
@C-Sophie : Est ce que ce ticket est toujours d'actualité ?

**Comment by fufeck** [comment]
> * Communauté urbaine de Dunkerque

Je m'en occupe
