### ISSUE TITLE
Le bouton "Publier une autre BAL"  ne ramène pas au début du formulaire.

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/adresse.data.gouv.fr#1532]
Comportement attendu : 
- on publie une bal
- on clique sur  :
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/95912586/a7f9bb14-79b4-46cb-9d58-02d1f279af48)
- on retourne à la première étape ou l'on choisi le fichier BAL
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/95912586/0c09af1b-ffa6-477d-86c1-7734f808e483)

Comportement observé :
- on publie une bal
- on clique sur  :
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/95912586/a7f9bb14-79b4-46cb-9d58-02d1f279af48)
- on reste sur la même page, le bouton pointe vers : 
https://adresse.data.gouv.fr/bases-locales/publication
qui est la page déjà ouverte, donc pas de retour à la première étape de publication. On reste sur le message de confirmation de la publication précédente.
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/95912586/4ef6e272-5b74-4bcc-928e-fb61f7ca972e)

**Comment by MaGOs92** [comment]
Done!
