### ISSUE TITLE
Auto complete ne marche pas sur toutes les rues de certaines communes référencé BAL - EX Trappes 78190

### ISSUE THREAD

**Issue by oussamasse** [BaseAdresseNationale/adresse.data.gouv.fr#1534]
Bonjour,

J'ouvre ce ticket pour remonté un dysfonctionnement de l'auto complete dans le site /BAN 
https://adresse.data.gouv.fr/base-adresse-nationale
En effet, plusieurs communes notamment celle qui m'intéresse : Trappes dans le département des Yvelines, en Île-de-France, 
Code postal : 78190, Insee : 78621 
Ne remonte aucune adresse dans l'auto complete, même si les adresses existent et bien référencés BAL
Ce qui est BLOQUANT dans plusieurs démarches administratives.
"3643 numéros répertoriés"
"218 voies répertoriées"

Quelqu'un pourra prendre en charge la correction s'il vous plaît ? 
Merci d'avance !

**Comment by guillaumj** [comment]
Bonjour, 

Je confirme le problème remonté par @oussamasse.

Nous n'avons aucun résultat dans l'autocomplete sur toute la commune de Trappes et ses alentours (Guyancourt, Elancourt, Maurepas etc.) depuis vendredi dernier (2 juin), ce qui rend inopérant plusieurs services publics à destination des usagers de ces communes.

**Exemple « Rue des Epices, 78190 Trappes » :** 
- Accessible sur la carte : https://adresse.data.gouv.fr/base-adresse-nationale/78621_0244_00003
- Mais aucun résultat dans l'API : https://api-adresse.data.gouv.fr/search/?q=Rue%20des%20Epices,%2078190%20Trappes

Est-ce un problème suite à une mise à jour de la BAL par les communes ?

**Comment by mmortier** [comment]
Apparemment le problème est corrigé. Le geocodeur a du être rechargé.
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/7045982/da90e6fb-d0dd-47bc-ba1b-83b549580ca7)
