### ISSUE TITLE
Ajout de Terres de confluences aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1536]
## Nouveau partenaire

- Nom : Terres de confluences
- Description : Le service SIG sensibilise et accompagne ses communes membres dans l’élaboration de leur Base Adresse Locale. Elle propose des formations et un support sur l’outil « Mes Adresses ». Elle met à disposition ses compétences techniques en matière d’information géographique et peut ponctuellement réaliser une partie de la mise à jour des adresses.
- Lien vers le site : https://www.terresdesconfluences.fr/
- Lien vers la charte :
- Date de signature de la charte : 08/06/2023
- Périmètre : Communauté de Communes Terres des Confluences (22 communes)
- Liste des codes département : 81
- Échelon : 1
- Est-ce un acteur privé ? : non
- Liste des mots clés : #Formation #AccompagnementTechnique #RéalisationDeBasesAdressesLocales

Ajouter ici le logo du partenaire
![LOGO-TerresdesConfluences-fond-blanc](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/dd5090c0-2f26-4f69-bb6a-f5c3af3537f4)

**Comment by MaGOs92** [comment]
C'est fait!
