### ISSUE TITLE
bug d'affichage dans l'explorateur au changement de fond carto

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1552]
Lors qu'on choisit l'affichage source : 
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/7045982/c82de4c8-eec1-44bf-9a77-7e5587b941a2)

et qu'on change de fond carto 
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/7045982/17df6e0a-2cc8-4596-a00b-2d6092e8fa1a)

La légende reste sur sources mais elle correspond en fait aux couleurs de certification.
Pour résumer : on change de fond et on revient sur la sélection affichage certification (même si on était en affichage des adresses par sources).

**Comment by nkokla** [comment]
Le bug sera réglé avec le passage à React-map-GL : 
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1680

**Comment by mmortier** [comment]
résolu par la mise en prod du 09 janvier lié à cette PR https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1680
