### ISSUE TITLE
Correction sur la landing page

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1553]
- L'AITF n'a pas donné de réponse pour insérer le logo sur la landing page. Pour ne pas ralentir davantahe la mis een ligne : retirer le logo, quitte à la replacer au moment où une réponse arrivera. 
- Logo haute def AMF en copie au besoin
![Identité AMF](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/01327fbf-b170-46d9-b62c-139cb9919d0d)

Issue en référence : 
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1545

**Comment by MaGOs92** [comment]
done!
