### ISSUE TITLE
Ajout du SICTIAM aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1558]
## Nouveau partenaire

- Nom : SICTIAM
- Description : Établissement de services numériques du secteur public, avec plus de 450 institutions publiques et 4 départements adhérents, le SICTIAM propose aux communes un service d'adresse qui comprend la formation, la réalisation des Bases Adresses Locales sur un outil dédié et un accompagnement technique.
- Lien vers le site : https://catalogue.sictiam.fr/adressage-des-rues/
- Lien vers la charte : https://catalogue.sictiam.fr/adressage-des-rues/
- Date de signature de la charte : 25/06/2023
- Périmètre : Provence Alpes Côte d'Azur
- Liste des codes département : 04, 05, 06, 13, 83, 84.
- Échelon : 2
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Formation", "Accompagnement technique", "Réalisation des Bases Adresse Locales".

Ajouter ici le logo du partenaire
![logo_sictiam_22c](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/9df4cef1-5bda-4858-8aad-5c142ca29b5c)

**Comment by MaGOs92** [comment]
done!
