### ISSUE TITLE
Ajout de Gers numérique aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1559]
## Nouveau partenaire

- Nom : Gers numérique
- Description : Gers numérique propose un accompagnement pour les communes qui ne disposent pas des moyens techniques, financiers et humains pour réaliser cette activité (< 250 habitants dans un premier temps). 
- Lien vers le site : https://www.gersnumerique.fr/
- Lien vers la charte : https://www.gersnumerique.fr/bouquet-de-services/bouquet-de-services.html
- Date de signature de la charte : 06/06/2023
- Périmètre : communes du Gers
- Liste des codes département : 32
- Échelon : 2
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Formation", "Accompagnement technique", "Réalisation des Bases Adresse Locales"

Ajouter ici le logo du partenaire
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/7e01e5bc-6dc9-4f31-87f0-c52dd133edb7)

**Comment by MaGOs92** [comment]
done!
