### ISSUE TITLE
Ajout de Département du Loiret aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1562]
## Nouveau partenaire

- Nom : Département du Loiret 
- Description : Afin d'être identifiée et éligible à la fibre auprès des fournisseurs d'accès Internet, il est indispensable que l'adresse de chaque habitation puisse être référencée correctement. Il s'agit de créer pour les futurs abonnés, qu'ils soient particuliers ou entreprises, une adresse géolocalisable qui sera inscrite dans la Base d'Adresse Nationale (BAN).Dans ce cadre, le service en charge du SIG et du déploiement de la fibre du Conseil Départemental du Loiret accompagne les communes, via une assistance technique pour se lancer et prendre en main la gestion de ses adresses, afin de faciliter la bonne arrivée de la fibre sur l'ensemble de son périmètre d'action.
- Lien vers le site : https://www.loiret.fr/
- Lien vers la charte : https://geoloiret.loiret-numerique.fr/apps/projets/cd45_adressage.htm
- Date de signature de la charte 04/07/2023  
- Périmètre : communes du Loiret où la fibre sera déployée
- Liste des codes département : 45
- Échelon : 2
- Est-ce un acteur privé ? : non
- Liste des mots clés : Formation, Accompagnement technique

Ajouter ici le logo du partenaire
![logo-Loiret-quad](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/5cc2e1d5-5a16-4580-9b95-1cf3c690d2b4)

**Comment by vinsag** [comment]
@C-Sophie : le lien de la charte renvoie un module de connexion ou il faut annuler. J'ai récupéré le lien vers la charte directement: https://geoloiret.loiret-numerique.fr/arcgis/sharing/rest/content/items/3374ec07d23c4ed7bb041cc8310f7523/data
Faut il que je le remplace ou nous devons laisser le lien du ticket ?

**Comment by C-Sophie** [comment]
Effectivement le bon lien vers la charte est désormais https://geoloiret.loiret-numerique.fr/arcgis/sharing/rest/content/items/3374ec07d23c4ed7bb041cc8310f7523/data et le lien vers le site change aussi pour : https://geoloiret.loiret-numerique.fr/apps/projets/cd45_adressage.htm au lieu de https://www.loiret.fr/
