### ISSUE TITLE
Ajout de Communauté de communes de l’île de Ré aux partenaires de la Charte de la Base Adresse Locale

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1563]
## Nouveau partenaire

- Nom : Communauté de communes de l’île de Ré
- Description : Le service SIG de la Communauté de communes de l’île de Ré accompagne les communes adhérentes à la démarche intercommunale, dans la création et la tenue à jour de Bases Adresses Locales de qualité, via le SIG Web mutualisé et assure ainsi le meilleur accès aux services départementaux intervenant sur l’île de Ré.
- Lien vers le site : https://cdciledere.fr/la-ban-en-quelques-mots/
- Lien vers la charte : https://cdciledere.fr/app/uploads/2023/06/Charte-de-la-Base-Adresse-Locale-organisme-public.pdf
- Date de signature de la charte : 22/05/2023
- Périmètre : La Flotte, Les Portes en Ré, Rivedoux Plage, Saint Martin de Ré, Sainte Marie de Ré
- Liste des codes département : 17
- Échelon : 1
- Est-ce un acteur privé ? : non
- Liste des mots clés : "Accompagnement technique", "Réalisation des Bases Adresse Locales", "Mise à disposition d'outil mutualisé".

Ajouter ici le logo du partenaire
![cdc](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/58e308b0-d220-4360-ad74-7ac610e23e60)

**Comment by vinsag** [comment]
@C-Sophie : il manque la liste des mots clés pour l'ajout de cette communauté de communes

**Comment by C-Sophie** [comment]
Les mots clés sont ajoutés.
