### ISSUE TITLE
Améliorer la visibilité générale des communes dans l'explorateur

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1565]
besoin exprimé en Adresse_lab Mai 2023
"Sur la carte, serait il possible d'afficher le nom des communes à partir d'une certaine échelle pour faciliter la navigation? "

La situation actuelle (voir image ci-dessous) n'est pas satisfaisante pour se repérer à la commune : 
Adapter la visualisation à l'échelle pour plus de lisibilité. 
sur les petites échelles, (niveaux 5, 6, 7 ? à définir) ne faire apparaitre que le nom de la commune et pas les lieux-dits. 

![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/97727151/a1a9f56d-46f3-4594-a6dc-65252dddb46c)

**Comment by mmortier** [comment]
@FrederiqWilliams les niveaux 5,6,7 ne font pas apparaitre les lieux dits. 
Les lieux-dits apparaissent au niveau 10.
Au niveau 11 on a les voies et les lieux-dits.
Tu veux qu'on change au niveau 10 pour remplacer les LD par les noms des communes?

**Comment by FrederiqWilliams** [comment]
oui c'est ça. Je propose les modifications suivantes : 
L9 : faire apparaitre contours et noms des communes. Enlever le nom "France"
L10 : ne pas faire apparaitre les LD, faire apparaitre uniquement les noms de communes (les contours y sont)
L11 : mettre les LD et les VLD de la même taille

**Comment by vinsag** [comment]
@FrederiqWilliams : Voici les changements que j'ai effectué:
- L12 : mise en place des voies
- L11 : Mise en place des lieux dits
- L9: Commune
- L3 max L4: France et Monaco apparaissent
