### ISSUE TITLE
Ajouter le point d'étape Adresse_lab T3 de Septembre aux evenements

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1566]
Titre : Adresse_Lab
Subtitle : Point d'échange trimestriel T3 2023

Le Mardi 26 Septembre de 15h à 16h30
Evenement en ligne

Cible : Les utilisateurs de la donnée adresse
mots-clés : Technique/Utilisateurs/BAN
Lien visio : https://webinaire.numerique.gouv.fr//meeting/signin/5699/creator/3324/hash/61fcf6f21947874ba68b105a3433cdd55e43ffb9

SI possible modifier l'intitulé du bouton "s'inscrire" en "Rejoindre", et pointer directement sur le lien de la visio.

**Comment by vinsag** [comment]
@FrederiqWilliams : quelle est la description de l'évènement ?

**Comment by FrederiqWilliams** [comment]
Point d'étape trimestre 3 : actualités et chantiers en cours

**Comment by mmortier** [comment]
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1572
