### ISSUE TITLE
Mettre en place une base de données structurée des utilisateurs de la BAN

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1571]
Objectif = valorisation des usages
- une base de données
- une articulation avec la page thématique du site
- une interface pour les utilisateurs de la BAN
- un moteur de recherche pour accéder à l'information

**Je suis chargé de déploiement BAN** : 
- outil de gestion de la communauté d’utilisateurs
- alimenter la page du site correspondante

**Je suis un particulier ou une commune**
Besoin : retrouver mon adresse dans les différents systèmes d'information. 
Savoir si l'acteur utilise la BAN, la fréquence d'actualisation, pouvoir lui signaler que mon adresse BAL n'est pas dans sa base. 

**Je suis un utilisateur**
décrire mon usage de la donnée
rentrer les informations

colonnes à prévoir : 
Nom/logo/type d'utilisation/fréquence d'actualisation/mots-clé pour moteur de recherche/url de visu
Une ligne par type d'utilisation/produit (une ligne par utilisateur n'est pas suffisant)

(analyse à mener)

**Comment by mmortier** [comment]
Analyse préalable à faire

**Comment by FrederiqWilliams** [comment]
update nov 2023. 
La base est en place. 
Reste à définir 
- la liaison avec la page "usages"
- la liaison avec le script de levée des quotas pour l'API adresse (white-list)

**Comment by mmortier** [comment]
L'objet du ticket est rempli. Créer de nouveaux tickets pour ces liens @FrederiqWilliams
