### ISSUE TITLE
mettre une capture d'écran des chiffre de juin

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1574]

**Comment by mmortier** [comment]
En attente de la réparation de grafana

**Comment by mmortier** [comment]
Le chargement des logs a été débloqué la semaine dernière mais il n'y a pas eu de rattrapage pour les données non chargées dans grafana sur juin et juillet. On ne peut pas mettre à jour.

**Comment by vinsag** [comment]
On peut fermer ce ticket comme nous ne pourrons pas récupérer les stats.

**Comment by mmortier** [comment]
Grafana n'a pas pu récupérer les log
