### ISSUE TITLE
Correction de la page du partenaire Somme numérique

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1579]
**Sur la page :** 
https://adresse.data.gouv.fr/bases-locales/charte/organismes

**Remplacer le texte de l'offre** 
" Somme numérique accompagne gratuitement ses membres et leurs communes dans le but de faciliter le déploiement de la fibre" par 
" Somme Numérique propose conseils et prestations d'accompagnement à ses membres et leurs communes dans le but de faciliter le déploiement de la fibre"

**Comment by MaGOs92** [comment]
Done!
