### ISSUE TITLE
Ajout du lien "Voir en grand écran" sur la carte de la page du blog

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1593]
La page du blog ne propose pas le lien "voir en grand" que proposait le billet de blog (dépublié)
https://adresse.data.gouv.fr/blog

Il est difficile de zoomer et dézoomer correctement dans le rectangle et préférable de consulter sur uMap. 
La capture ci dessous est celle du billet de blog avec voir en grand écran

Le lien associé : https://umap.openstreetmap.fr/en/map/carte-des-temoignages_953200#6/46.149/8.240

![Capture d’écran du 2023-08-29 10-19-23](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/1f1bf118-08f2-4fe2-87cb-1df50c7819ed)

**Comment by MaGOs92** [comment]
done
