### ISSUE TITLE
Ajouter le champ type d'adresse

### ISSUE THREAD

**Issue by jonathan-vandal** [BaseAdresseNationale/adresse.data.gouv.fr#1603]
Bonjour, 

J'utilise l'API `https://api-adresse.data.gouv.fr/search` et dans mon application je découpe l'adresse en plusieurs partie : 
numéro voie : 15
type voie : Avenue
nom voie : de Versailles

Lors de la réponse je peux faire une extraction via `street: "avenue de Versailles"`. Ça fonctionne mais c'est un peu archaïque, est ce que vous avez la possibilité de rajouter le type de voie dans un champ séparé pour un meilleur découpage ? Et si possible faire de même pour le code départementale qui faut extraire via le contexte `context : "33, Gironde, Nouvelle-Aquitaine"` ca serait bien d'avoir un champ dédié.

Merci :)

**Comment by FrederiqWilliams** [comment]
Bonjour, 
L'approche est délibérément de ne pas utiliser de classification des voies par une typologie. 
Le type de voie fait partie intégrante du libellé de l'adresse, une extraction sur ce champ n'est donc pas possible
