### ISSUE TITLE
Indexer la Carte des Partenaires de la Charte de la Base Adresse Locale sur adresse.data.gouv.fr

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#1609]
Référencer la carte des Partenaires de la Charte de la Base Adresse Locale sur la page des Partenaires de la Charte (organismes à but non lucratif et communes) ou sur la landing page à votre convenance : 
https://umap.openstreetmap.fr/en/map/partenaires-publics-de-la-charte-de-la-base-adress_953281#6/47.354/9.229

Sur la landing page, ce cadre permet a minima un lien :
![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/69309231/16edfb3f-738b-48d5-bdf9-2ee2201ef546)

**Comment by MaGOs92** [comment]
Done!
