### ISSUE TITLE
Recherche par id

### ISSUE THREAD

**Issue by juchom** [BaseAdresseNationale/adresse.data.gouv.fr#1640]
Bonjour,

Serait-il possible d'offrir un moyen de retouver une adresse directement par son identifiant ?

Merci

**Comment by FrederiqWilliams** [comment]
Bonjour, 
la route suivante de consultation de la BAN permet de rentrer par les id (de commune, de voie, d'adresse) : 
https://plateforme.adresse.data.gouv.fr/lookup/{id}

Cordialement
