### ISSUE TITLE
Webinaires Mes Adresses décembre 2023

### ISSUE THREAD

**Issue by Ariane-Rose** [BaseAdresseNationale/adresse.data.gouv.fr#1645]
{
"title": "Webinaire Mes Adresses",
"subtitle": "Je débute sur Mes Adresses",
"description": "L’équipe du Programme Bases Adresses Locales propose aux communes qui le souhaitent un webinaire sur l'éditeur Mes Adresses. Au menu, un rappel des principales fonctionnalités et les points de vigilance qualité.",
"type": "formation",
"target": "communes",
"date": "2023-12-07",
"tags": [
"Programme Base Adresse Locale",
"Base Adresse Locale",
"Commune"
],
"isOnlineOnly": true,
"address": {
"nom": "",
"numero": "",
"voie": "",
"codePostal": "",
"commune": ""
},
"href": "https://cryptpad.fr/form/#/2/form/view/bsah2aYbXaFmMY6g5fPLFJSqiZw-IV8kVLDwpJ303po/",
"isSubscriptionClosed": false,
"instructions": "",
"startHour": "14:00",
"endHour": "15:30"
},
{
"title": "Webinaire Mes Adresses",
"subtitle": "Je veux améliorer ma BAL",
"description": "L’équipe du Programme Bases Adresses Locales propose aux communes qui le souhaitent un webinaire sur l'éditeur Mes Adresses. Au menu, un rappel des principales fonctionnalités et les points de vigilance qualité.",
"type": "formation",
"target": "communes",
"date": "2023-12-14",
"tags": [
"Programme Base Adresse Locale",
"Base Adresse Locale",
"Commune"
],
"isOnlineOnly": true,
"address": {
"nom": "",
"numero": "",
"voie": "",
"codePostal": "",
"commune": ""
},
"href":"https://cryptpad.fr/form/#/2/form/view/rmA72mt4hBBRkAvx+HnqMyQ+Btt-Olh-xsiVIkmUcfc/",
"isSubscriptionClosed": false,
"instructions": "",
"startHour": "14:00",
"endHour": "15:30"
},
{
"title": "Webinaire Mes Adresses",
"subtitle": "Je débute sur Mes Adresses",
"description": "L’équipe du Programme Bases Adresses Locales propose aux communes qui le souhaitent un webinaire sur l'éditeur Mes Adresses. Au menu, un rappel des principales fonctionnalités et les points de vigilance qualité.",
"type": "formation",
"target": "communes",
"date": "2023-12-21",
"tags": [
"Programme Base Adresse Locale",
"Base Adresse Locale",
"Commune"
],
"isOnlineOnly": true,
"address": {
"nom": "",
"numero": "",
"voie": "",
"codePostal": "",
"commune": ""
},
"href": "https://cryptpad.fr/form/#/2/form/view/H8XhRyeuKtkaAbOUL96KUsFiE-Vg4Zx3FHxD2j+TM9w/",
"isSubscriptionClosed": false,
"instructions": "",
"startHour": "14:00",
"endHour": "15:30"
}

**Comment by MaGOs92** [comment]
Done!
