### ISSUE TITLE
Nettoyage des dossiers de mise à disposition des exports

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1656]
Afin de gagner de la place sur les serveurs il est nécessaire d'optimiser la mise à disposition des fichiers d'exports qui sont présentés depuis 2019 sur https://adresse.data.gouv.fr/data/ban

![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/97727151/00501fa9-1700-47e4-bcf7-7d2583b3bea3)

Stratégie d'exposition : 
- Sur l'année en cours  et l'année N-1 : on garde la mise à disposition quotidienne et le latest de la semaine en cours, un fichier par semaine pour le reste de la période. 
- sur les années précédentes, soit de 2019 à déc 2021 : on n'expose plus qu'un fichier par mois, le premier fichier du mois. 

A reproduire sur les 3 dossiers : 
- adresses
- adresses-odbl
- export-api-gestion

**Comment by FrederiqWilliams** [comment]
Note : les fichiers odbl sont un renvoi sur les fichiers csv legacy. 
Cette route est inutile. Prévoir de la supprimer asap en prévenant les utilisateurs suffisamment à l'avance

**Comment by mmortier** [comment]
tant que la communication n'est pas faite 2 mois avant on ne peux pas nettoyer
