### ISSUE TITLE
certificat de numérotage : expérimentation

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/adresse.data.gouv.fr#1671]
Voir avec Chantal A. pour activer la fonctionnalité et les identifiant uniques sur Bayonne. _update : Réunion de cadrage janvier 2024_

**Comment by mmortier** [comment]
Réunion à prévoir en janvier

**Comment by FrederiqWilliams** [comment]
A lier au ticket https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1206. 
Renommer ce ticket en "certificat d'adressage", puisque les certificats de numérotation sont identifiés comme étant une autre fonctionnalité (publipostage pour information de numérotation) au niveau des outils producteurs.

**Comment by FrederiqWilliams** [comment]
cr point de janvier : spec de ce certificat : 

Le service juridique de la mairie de Bayonne a confirmé que : 
- le document n'a aucune forme définie par des textes
- une signature manuscrite n'est pas obligatoire.
-pour la cada (Commission d’accès aux Documents administratifs), il faut pouvoir faire une extraction de type « courrier » car envoyer les notaires sur https://adresse.data.gouv.fr/base-adresse-nationale  sans pouvoir faire "d'extraction" ne suffirait pas. 

Description fonctionnalité : 
-	Le service pourra être activé par commune, sur demande de la mairie 
-	Production des certificats possible uniquement sur les adresses certifiées, avec une parcelle cadastrale renseignée. 
-	Edition automatique, en ligne. A partir de l’explorateur, et déclenché par n’importe qui (service « Grand Public). 
-	La mairie n’a pas besoin de valider chaque demande, mais est intéressée par la possibilité d’accéder à une liste des demandes 
-	La mise en forme du document est à finaliser, notamment pour lui conférer un caractère un peu plus formel et « officiel » (valeur administrative). cf exemples joints
[certificat de numérotage-pau1.pdf](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/files/14138180/certificat.de.numerotage-pau1.pdf)
[exemple_CN.pdf](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/files/14138181/exemple_CN.pdf)

-	La production de ce document est rendue possible à partir de la nouvelle infrastructure BAN mise en place pour accueillir les nouveaux identifiants. Le corollaire est qu’il est nécessaire au préalable pour la BAL concernée d’avoir intégré ce nouveau processus d’identification.

**Comment by vinsag** [comment]
- Refaire la maquette pour avoir un document officiel
- Mettre en place pour les communes qui veulent l'activer dans les paramètres

**Comment by vinsag** [comment]
Pour faire générer le PDF de la certification
1) Récupérer le logo de la commune via l'annuaire des collectivités : https://gitlab.com/incubateur-territoires/startups/annuaire-des-collectivites/api
2) Bouton à réactiver pour la ville de Bayonne "Certification" sur la page de l'explorateur
3) Modifier le contenu de la page certification en fonction du PDF fourni en pièce jointe
4) Stocker les informations de la mairie dans une base de données postgres : service mairie, tel, mail
5) Enregistrer les demandes dans une table postgres avec : id_demande(nanoid) l'identifiant de l'adresse, copie de l'adresse et des parcelles,
6) Générer un nanoId pour l’identifiant de la demande.
7) Generer un QRCode et mettre l'url pour vérifier [l'authenticité[](url)](

[CertificatNumerotage.pdf](https://github.com/user-attachments/files/16069886/CertificatNumerotage.pdf)
