### ISSUE TITLE
Ajout stat commune utilisant identifiant unique

### ISSUE THREAD

**Issue by vinsag** [BaseAdresseNationale/adresse.data.gouv.fr#1729]
Nous avons besoin de connaitre le nombre de communes utilisant les identifiants unique

**Comment by vinsag** [comment]
- Integrer les stats sur la page de stats
- Ajouter un camembert sur la page deploiement.

**Comment by antoineludeau** [comment]
Il a été décidé de mettre les stats seulement sur la page `/deploiement-bal`

**Comment by vinsag** [comment]
Livré en production, je ferme le ticket
