### ISSUE TITLE
Optimisation des noms des sources sur l'explorateur

### ISSUE THREAD

**Issue by vinsag** [BaseAdresseNationale/adresse.data.gouv.fr#1731]
La Poste, INSEE et SDIS ne devraient plus être dans les sources. (les données ont été intégrées dans les données de la base de l'IGN lors de l'initialisation)
Vérifier dans la base si on trouve toujours ces valeurs, si non les supprimer de la liste.
Ensuite simplifier la liste des sources pour correspondre au process actuel :

Base Adresse Locale
IGN
Guichet Adresse
Cadastre
Opérateur THD

En fonction du nombre d'adresse par source, on pourra définir une sources Autres pour regrouper l'ensemble des sources en faible quanntité.

**Comment by jbouhadoun** [comment]
Voici les résultats :
    
    'Base Adresse Locale' : 16,409,460
    'IGN' : 8,282,548
    'Opérateur THD' : 7,353,294
    'Cadastre' : 6,996,380
    'Guichet Adresse' : 241,888
    'SDIS (Pompiers)' : 603
    'La Poste' : 294

**Comment by vinsag** [comment]
@FrederiqWilliams : Suite au résultat obtenu ci dessus, je propose de  créer une catégorie "Autres sources" qui englobera :
- La poste
- SDIS
- Guichet Adresse
Nous attendons ton retour pour faire les changements.

**Comment by FrederiqWilliams** [comment]
Il me semble important de garder (encore un peu) l'information relative au guichet adresse, qui représente un process particulier de production de la donnée et un travail déjà réalisé sous responsabilité des communes. 
Pour être au plus proche des process de production historique, je propose : 
- d'englober les données SDIS dans la source "IGN" (car les données auraient dû été intégrées à la base IGN lors de l'initialisation)
- d'englober les données source "La Poste" dans la source "Guichet Adresse" car c'était l'outil utilisé par La Poste en prestation pour les communes.
