### ISSUE TITLE
Problème d'automplete sur un nom partiel de commune

### ISSUE THREAD

**Issue by symac** [BaseAdresseNationale/adresse.data.gouv.fr#1740]
Bonjour,
j'espère être au bon endroit pour déclarer ce bug, sinon n'hésitez pas à réorienter. En faisant des test sur l'API search pour l'utiliser dans le cadre d'un autocomplete je constate un problème au niveau des suggestions, visible sur le démonstrateur de la base adresse : https://adresse.data.gouv.fr/base-adresse-nationale

Si je souhaite chercher la commune de Talence, j'ai une évolution de résultats au cours de ma saisie qui m'interpellent : 

- Talen : j'ai plusieurs résultats dont un de commune pour Talence, jusqu'ici tout va bien;
- Talenc : la commune de Talence a disparu et je n'ai plus qu'un résultat, une rue Talencourt dans les Vosges;
- Talence : la commune est de retour, tout va bien;

Ça manque de cohérence pour l'utilisateur, a priori c'est bien lié aux appels API, puisque https://api-adresse.data.gouv.fr/search/?q=Talenc&limit=7 ne renvoie que ce résultat dans les Vosges et ne donne aucune trace de la commune de Talence.

Est-ce que c'est un bug connu ou bien est-ce qu'il y a quelque chose qui m'échappe dans la manière dont est censé fonctionner cette autocomplétion ?

**Comment by FrederiqWilliams** [comment]
Bonjour, 

Merci de votre retour. C'est bien un fonctionnement anormal, qui est identifié mais pas résolu. 
Il semble provenir d'un paramétrage de l'auto-complétion dans le moteur Addok, qui n'est pas forcément adapté aux particularités phonétiques française. 

Ainsi lorsque la chaine de caractères de la recherche se termine par un c , nous avons constaté qu'il ne renvoie plus les phonèmes prononçant le c comme "ss" mais uniquement ceux intégrant la lecture du "c" comme un son "k". 

ex pour Talenc, mais nous l'avons constaté également pour Annec (il ne trouve pas Annecy), Mennec (Il ne trouve pas Mennecy mais trouve Menecourt, etc...)

C'est une évolution du moteur qu'il faudrait considérer. 
Mais il n'y a pas de ressources de développement identifiée sur cet outil pour l'instant.

**Comment by symac** [comment]
@FrederiqWilliams merci pour ce retour, je vais peut-être voir comment combiner recherche des villes via ma BDD locale et recherche adresse via l'API adresse alors. Et je clos donc l'issue si le bug est connu, merci.
