### ISSUE TITLE
Ajouter la date de dernière actualisation du moteur de recherche à l'entrée de l'explorateur,  et sur la page de l'API

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1766]
Les données de la BAN sont actualisées en continu. 
Le moteur de recherche est actualisé en ce moment tous les  8 à 15 jours, ce qui crée un écart de fraicheur lors des recherches d'adresse, et des questionnements des utilisateurs. (situation cible = actualisation hebdo)

Proposition de renseigner la date d'actualisation du moteur pour information des utilisateurs de l'API. 
Mention = "Dernière actualisation du moteur de recherche : {date : Jour/mois/année/heure/min}"

La date de dernière actualisation est accessible ici : https://api-adresse.data.gouv.fr/info.txt

Mettre cette mention à deux endroits : 
- sur la page d'accueil, https://adresse.data.gouv.fr/
sur l'accès à l'explorateur, juste au dessus de la barre de recherche

![image](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/assets/97727151/940fd360-3299-4d87-8c47-576adde09667)

- sur la page https://adresse.data.gouv.fr/api-doc/adresse, juste en dessous du bandeau bleu

**Comment by vinsag** [comment]
@FrederiqWilliams : sur la page d'accueil, ou veux tu mettre l'information en dessous du bouton ou au dessus du champ de recherche ?

**Comment by FrederiqWilliams** [comment]
Juste au-dessus de la barre de recherche, et en dessous de la phrase d'accueil "Rechercher une adresse..."
