### ISSUE TITLE
[Question/Evolution] Ajout de l'UUID dans l'export CSV + Fiabilité de l'UUID

### ISSUE THREAD

**Issue by JulienThilliezLM2** [BaseAdresseNationale/adresse.data.gouv.fr#1810]
Bonjour,

Nous envisageons d'utiliser l'UUID comme clé de synchronisation entre les identifiants internes de l'entreprise et la BAN. L'idée d'utiliser cet UUID plutôt que la clé d'interopérabilité était de rendre le système plus résilient face aux changements de clé (Cf. [ici](https://doc.adresse.data.gouv.fr/utiliser-la-base-adresse-nationale/identifiants-gestion-et-guide-pratique/faq-identifiants)).

Cet identifiant n'est pas exporté dans les CSV. Est-ce intentionnel ? Son exportation pourrait faciliter l'adoption, non ?

En analysant l'export Addok pour l'Ain, nous avons remarqué que près de 33 % des housenumbers pour l'Ain n'ont pas d'UUID. Savez-vous si cela est normal ? Utiliser l'UUID pour la synchronisation entre nos systèmes et la BAN vous semble-t-il pertinent, ou la fiabilité de ce mécanisme ne le permet-elle pas ?

Merci par avance.

**Comment by FrederiqWilliams** [comment]
Bonjour Julien,  

C'est tout-à-fait l'objectif de ce nouvel identifiant de jouer le rôle de pivot entre les données BAN et vos données systèmes pour en faciliter la synchronisation, nous vous encourageons donc fortement à l'utiliser. 
L'objectif est bien qu'il soit déployé sur l'ensemble des données de la BAN, c'est un déploiement progressif puisque ce sont les producteurs des BAL qui intègrent cet identifiant au fur et à mesure de la publication. 
Nous avons rajouté dans nos statistiques des éléments de suivi de la progression de cet identifiant : https://adresse.data.gouv.fr/deploiement-bal

La mise en place de l’identifiant dans une infrastructure déjà existante et utilisée est complexe, nous avançons avec précaution pour ne pas déstabiliser les usages en place.  Nous n'avons donc pas intégré les identifiants dans les exports csv actuels pour ne pas briser la rétrocompatibilité. Vous trouverez les UUID dans un export spécifique temporaire qui est ici : https://adresse.data.gouv.fr/data/ban/adresses/latest/csv-with-ids
Ils sont également intégrés dans les fichiers Addok comme vous l'avez constaté. 

Nous travaillons en parallèle à la mise en place d'un nouveau format d'export (json) qui permettra de récupérer cette information de façon plus pertinente et associée aux informations d'historique : différentiel entre deux versions de la BAN. 

A votre disposition pour davantage d'informations si besoin. 
Vous pouvez joindre l'équipe sur l'adresse mail du support adresse@data.gouv.fr

Cordialement,

**Comment by JulienThilliezLM2** [comment]
Bonjour Frédérique,

Merci pour ce retour particulièrement complet ! On va conserver la trajectoire, et on attend avec impatience la suite !

Bonne continuation,
Julien
