### ISSUE TITLE
Affichage de positions multiples pour une même adresse

### ISSUE THREAD

**Issue by benoit-dd** [BaseAdresseNationale/adresse.data.gouv.fr#1847]
J’ai été tenté de signaler des adresses superposées/mal placées avant de me rendre compte que la commune avait fait un double travail de localisation à la fois sur le point d’accès et sur le bâtiment.

Cependant, ni « mes signalements » ([Mes Signalements](https://mes-signalements.mes-adresses.fr/#/73303_0042)) ni « adresse.data.gouv » ([Rue des Aravis, Ugine (73303) - Base Adresse Nationale | adresse.data.gouv.fr 1](https://adresse.data.gouv.fr/base-adresse-nationale/73303_0042#17.19/45.757159/6.42163)) ne mettent en évidence l’existence de cette double typologie de positions. C’est semble-t-il le point d’entrée qui est privilégié. On ne voit les autres types qu’une fois un point sélectionné:
![1cbf3541eee94c6d596d351e81b740b883da0fda](https://github.com/user-attachments/assets/3f2832a0-7fd9-4f6d-bb3b-51ec2586a962)

Serait-il envisageable d’avoir un affichage par couleur par exemple qui montre immédiatement les différentes positions?

éventuellement uniquement à l’échelle de la rue pour éviter un trop grand fouilli, ou par un choix par case à cocher pour afficher un ou plusieurs types?

**Comment by FrederiqWilliams** [comment]
Bonjour, 
Cet arbitrage a été fait afin de ne pas surcharger l'affichage. Afficher l'ensemble des positions donnerait l'impression de doublons puisque chaque point porte son numéro. 
La position privilégiée est celle qui figure en première position dans le fichier BAL de la commune, en général celle qui correspond au point d'accès. Les autres positions, avec un code couleur,  apparaissent uniquement sur sélection de l'adresse.
