### ISSUE TITLE
[Refonte] texte de la page "mentions légales"

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1858]
voilà le texte à mettre en place pour la page "Mentions légales" - revue par la Mission juridique de l'IGN. 
[pour publi _Base Adresse Nationale - Mentions légales_revIGN.docx](https://github.com/user-attachments/files/17415037/pour.publi._Base.Adresse.Nationale.-.Mentions.legales_revIGN.docx)

Les deux autres pages "CGU" et "RGPD" sont en cours de rédaction et doivent faire l'objet d'une validation avec l'ANCT, on les mettra en place un peu plus tard. (après le déploiement du site)

**Comment by vinsag** [comment]
En attente des pages CGU et RGPD, il faudra ajouter un lien RGPD dans le footer
