### ISSUE TITLE
Ajout dans les évenements de la rencontre des utilisateurs nationaux du 05 dec

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/adresse.data.gouv.fr#1886]
Titre : Adresse_Lab
Subtitle : Rencontre Utilisateurs Nationaux BAN#6

Description :
Journée d'échanges entre les utilisateurs experts, autour des problématiques communes :
emprise d’utilisation large incluant des données d’assemblage, besoin d’historisation de la donnée, adosser des données métier aux adresses de la BAN, besoins spécifiques sur la qualité et la mise à jour des données.

Le Jeudi 05 Déc 2024, de 9h30 à 16h
Lieu : IGN, 73 Avenue de Paris, 94160 Saint-Mandé

Cible : Les SI nationaux utilisateurs avancés de la donnée adresse
mots-clés : Technique/Utilisateurs/BAN

**Comment by vinsag** [comment]
Finalise
