### ISSUE TITLE
Remplacer les deux hyperliens pour la barre de recherche par un bon gros bouton

### ISSUE THREAD

**Issue by vinsag** [BaseAdresseNationale/adresse.data.gouv.fr#1928]

**Comment by nkokla** [comment]
@vinsag
Finalement, après avoir passé cette modif, on retrouve le problème du site actuel : 
Le bouton "Vérifier mon adresse" semble être le bouton de validation (submit) du champs de recherche. 

C'était justement la raison pour laquelle on avait choisie d'utiliser des lien plutôt que des boutons sur ce bloc.

**Comment by vinsag** [comment]
Suite à ton message, nous allons donc revenir en arrière, je fais la PR

**Comment by vinsag** [comment]
Je ferme la demande comme les boutons ne correspondent plus à la recherche.
