### ISSUE TITLE
Filtre type=housenumber ne fonctionne pas

### ISSUE THREAD

**Issue by Pro-Jerome** [BaseAdresseNationale/adresse.data.gouv.fr#217]
Bonjour,

Lors de requêtes de géolocalisation en utilisant votre API, nous ne parvenons pas à filtrer les résultats sur le type=housenumber.
Tous les autres type sont bien filtrés.

Voici un exemple :
`https://api-adresse.data.gouv.fr/search/?q=7+rue+boulevard+jourdan+Paris+75014&type=housenumber`

Le deuxième résultat est de type locality.

Cela semble lié a https://github.com/etalab/adresse.data.gouv.fr/issues/112 et https://github.com/etalab/adresse.data.gouv.fr/issues/111.

Cordialement.

ps: le mail support[at]data.gouv.fr ne fonctionne pas.

Le probleme est liée au moteur addok : https://github.com/addok/addok/issues/478

**Comment by cyrilchapon** [comment]
1 an plus tard, celà ne fonctionne toujours pas

**Comment by parville** [comment]
A la réflexion,  pour répondre  "ProJerome" je suis choqué par le contre-exemple fourni. 
Ceci n'est pas une requête de géocodage !
C'est du pompage pur et simple sans valeur ajoutée ! 
Vous n'avez qu'à charger la source si tel est votre besoin élémentaire.

**Comment by cyrilchapon** [comment]
@parville , aucun rapport avec le sujet présent.

Voici un exemple "plus adapté au géocodage" (même si cette conversation n'a rien à faire dans un issue sur le fonctionnement de l'API proposée) : https://api-adresse.data.gouv.fr/search/?q=3%20rue%20nationale%20Lille&limit=5&type=housenumber

**Comment by cyrilchapon** [comment]
@jdesboeufs OK. Je vais tenter de voir si je peux y faire quelque chose dans Addok.

Merci 🙂

**Comment by cquest** [comment]
C'est corrigé par https://github.com/addok/addok/commit/9653811e52d6b1db76e970d254a565abc9ed5e66 et prochainement dans la 1.1rc2 avant la 1.1

**Comment by jdesboeufs** [comment]
@cquest tu nous tiens au courant pour le 1.1 ?

**Comment by thomasnoel** [comment]
Juste pour info, je pense que c'est normal car rien n'a été mergé, mais ça répond toujours de travers, par exemple sur https://api-adresse.data.gouv.fr/search/?q=de%20gaulle&limit=5&type=housenumber on reçoit des type:street.

**Comment by FrederiqWilliams** [comment]
La version d'addok 1.1 a été publiée, ça a du intégrer la résolution du problème.
