### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by Epistol** [BaseAdresseNationale/adresse.data.gouv.fr#362]
Hello there and congrats for the great work, it's amazing to have finally a simple api to get adresses. 

However, could we have the repo in english too ? Github is mainly maintained by english speaking people and in the case of people wanting to help, it'll be better to have it english.

Furthermore, a better documentation in the readme would be more than welcome, especially the api routes, which you could use to display on the website https://adresse.data.gouv.fr/api

**Comment by mmortier** [comment]
Bonjour,
Nous travaillons a l'amélioration de nos documentations des API continuellement.
Une page en anglais est également prévue à destination des réutilisateurs. https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1074

Je clos le ticket.
