### ISSUE TITLE
Absence des points de voies sans adresses (code 99999) dans les fichiers d'export

### ISSUE THREAD

**Issue by MarHoff** [BaseAdresseNationale/adresse.data.gouv.fr#604]
Bonjour,

Sur mon territoire je constate que la BAL mise en place par Mulhouse Alsace Agglomération contient plusieurs rues sans adresse codifiées avec le numéro 99999 conformément au format d'échanges BAL 1.1 (si j'ai bien compris).
Voir BAL : https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees/5d72f6789ce2e74868d00585

Néanmoins je constate que les points correspondant ne sont diffusés ni dans le fichier d'export adresse "adresses-68.csv", ni dans le fichier lieux dit "lieux-dits-68-beta.csv".
Est-ce normal et cohérent? Si ces entrées sont saisies par l'EPCI dans leur BAL on devrait pouvoir les récupérer dans l'export des données nationales.

Par exemple se référer aux clés interop "68154_0910_99999" ou "68154_0014_99999".

Bien cordialement

PS: Ci-dessous une capture d'écran des deux cle_interop citée ci-dessus après un chargement fructueux du fichier d'export BAL de la m2a dans éditeur.adresse.data.gouv.fr
<img width="1792" alt="Capture d’écran 2020-03-10 à 10 22 20" src="https://user-images.githubusercontent.com/4598589/76298031-1e987080-62b9-11ea-9118-9ada508cab92.png">

On peut constater qu'ils sont pris en compte dans l'interface d'édition.
Je suis en phase de formation en suivant la MOOC du CRIGE Normandie (https://www.crige.normandie.fr/crige/actions/actions_en_cours/mooc_adresse) et je teste des points problématique sur mon territoire désolé si je suis maladroit et/ou que je ne poste pas au bon endroit!

**Comment by MarHoff** [comment]
Bonjour, je confirme que ce comportement est toujours vérifiable à l'heure actuelle et s'avère assez problématique.
Testé avec la base locale de Mulhouse du 4janvier 2021 et l'export national du 8 février 2021.

Dois je répercuter cette information ailleurs pour une meilleure prise en compte?

**Comment by MaelREBOUX** [comment]
@jdesboeufs : tu pourrais nous confirmer que les traitements BAL -> BAN dégomment les adresses en 99999 STP ?

**Comment by jdesboeufs** [comment]
Les 99999 sont présents dans les fichiers `lieux-dits-XX-beta.csv.gz` sous une forme adaptée.
Il n'était pas possible d'ajouter les 99999 directement dans le fichier `adresses-XX.csv.gz` pour des questions de compatibilité SPD.

Par contre c'est le moment de proposer un export compatible BAL (en plus de l'historique).

**Comment by MaelREBOUX** [comment]
merci Jérôme.

la réponse de l'API est :

```json
{
	"type": "FeatureCollection",
	"version": "draft",
	"features": [{
		"type": "Feature",
		"geometry": {
			"type": "Point",
			"coordinates": [7.34775, 47.769665]
		},
		"properties": {
			"label": "Rue du Soleil 68110 Illzach",
			"score": 0.8599081818181817,
			"type": "locality",
			"importance": 0.45899,
			"id": "68154_0910",
			"name": "Rue du Soleil",
			"postcode": "68110",
			"citycode": "68154",
			"x": 1025498.08,
			"y": 6749993.55,
			"city": "Illzach",
			"context": "68, Haut-Rhin, Grand Est"
		}
	}],
	"attribution": "BAN",
	"licence": "ETALAB-2.0",
	"query": "rue du soleil",
	"filters": {
		"citycode": "68154"
	},
	"limit": 5
}
```

à part le ```"type": "locality"```  qui pourrait effectivement être ```street``` (ou autre chose ?) pour mieux filtrer on a un XY qui permet de faire qqch il me semble.

Que vous manque-t'il Martin ?

**Comment by jdesboeufs** [comment]
Concernant la "rue du soleil", on la voit en effet sur la carte, même si je l'accorde c'est écrit petit.

<img width="1439" alt="Capture d’écran 2021-04-07 à 11 23 13" src="https://user-images.githubusercontent.com/1231232/113843175-a6d69700-9793-11eb-837e-2464f655f912.png">

Et oui le type est `locality` pour les "voies sans adresses" qui sont dans la majorité des cas des lieux-dits/toponymes.

**Comment by MarHoff** [comment]
Pour le site web le soucis porte sur la recherche, effectivement si on sait exactement ce qu'on cherche et/ou la localisation on va trouver.
https://adresse.data.gouv.fr/base-adresse-nationale/68154_0910

Mais dans un cas d'utilisation plus réaliste on recherche la rue avec le champ de recherche et on ne trouve rien puisque l’autocomplétion ne permet pas de trouver la rue concernée!

![image](https://user-images.githubusercontent.com/4598589/113844100-6e838880-9794-11eb-9d1b-a02c099e63a6.png)
![image](https://user-images.githubusercontent.com/4598589/113844959-4e07fe00-9795-11eb-92e2-03d8efa8144f.png)

**Comment by MarHoff** [comment]
Pour ce qui est du fichier d'export, si je comprend bien, si je veux récupérer l'ensemble des rue pour une réutilisation je devrait télécharger le fichier "lieux dits" en beta (ce n'est pas très engageant pour une utilisation en production).

Mais j'ai peur que le fichier des lieux dits me fasse intégrer des localisation peut fiable et qui ne rentre pas dans le scope de mon usage. Ce que je cherche ce sont les adresses officielles et une localisation basique pour les rues sans adresses disposant d'un nom AFNOR fiable. Le fichier BAN "Fichier d’usage général recommandé dans la majorité des cas" me semblait donc le choix le plus logique.

**Comment by jdesboeufs** [comment]
Pour la recherche sur le site, c'est corrigé à l'instant.
#794

**Comment by jdesboeufs** [comment]
C'est bien ces fichiers.
Il faut comprendre que nous avons un engagement de stabilité sur ce format, et l'apparition de lignes avec des numéro 99999 ou sans numéros aurait provoqué des remous.
Le nom du fichier mentionne `beta` mais n'a pas changé depuis plus d'un an.
Comme j'indiquais à @MaelREBOUX il est temps de proposer un nouveau fichier "nouvelle génération", qui prendrait le relais de l'ancien, mais qui resterait maintenu.

**Comment by FrederiqWilliams** [comment]
Le nouvel export au format BAL 1.3 intègre les LD avec les numéros en 99999. Ce ticket peut être fermé.
