### ISSUE TITLE
BAN versus BAN ODBL : modalités de dédoublonnage (arbitrage entre géolocs)

### ISSUE THREAD

**Issue by PaulArchambault** [BaseAdresseNationale/adresse.data.gouv.fr#608]
Bonjour,

Je cherche une documentation qui explique comment l’on passe de la BAN complète  (qui comprends 49 M points avec doublons géoloc sur une même adresse) à la BAN "ODBL" (25 M de points uniques).
Sur quelle base est fait le choix du points de référence pour la version ODBL ?

Quelle est la clef de rapprochement entre les deux bases : la clef d'interopérabilité ? Pourquoi ne retrouve t-on pas l'identifiant BAN dans BAN ODBL ?

Merci pour vos lumières

**Comment by mmortier** [comment]
Ceci est plutôt une question à destination du support adresse@data.gouv.fr pas l'objet d'un ticket github. Je clos le ticket.
