### ISSUE TITLE
Message informatif sur le validateur de BAL

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#694]
Plusieurs utilisateurs craignent de ne pas pouvoir publier leurs Bases Adresses Locales si le validateur renvoi des anomalies.

Ajouter un message expliquant la différence entre les anomalies et les erreurs permettrait de faire comprendre aux utilisateurs que leurs adresses peuvent être publiées malgré la présence d'anomalies.

**Comment by jdesboeufs** [comment]
Et peut-être un bloc qui dit si le fichier sera accepté ou pas, et si oui combien de lignes seront rejetées.
