### ISSUE TITLE
Erreur 500 lors de la demande de publication d'une BAL qui ne passe pas le validateur

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#756]
Lorsqu'un utilisateur souhaite publier sa Base Adresse Locale, si jamais celle-ci contient une erreur lors de son passage au validateur, il reçoit une erreur `500`.

**Comment by mmortier** [comment]
Via le formulaire de dépot avec une BAL non conforme j'ai un rapport d'erreur et non une erreur 500.
C'est via quel canal l'erreur 500?

**Comment by mmortier** [comment]
le formulaire de dépot et l'api de dépot ont été réécrits en janvier 2022.
A priori le bug ne se présente plus
