### ISSUE TITLE
Mise à jour de noms de communes dans la BAN

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#786]
Le Décret n° 2020-175 du 26 février 2020 portant changement du nom de communes liste les 11 Communes concernées :

Les communes de :
- Lasserade (Gers) ;
- Ports (Indre-et-Loire) ;
- Sainte-Croix (Saône-et-Loire) ;
- Laval (Isère) ;
- Saint-Gineis-en-Coiron (Ardèche) ;
- Saint-Flour (Puy-de-Dôme) ;
- Montignac (Dordogne) ;
- Saint-Maime-de-Péreyrol (Dordogne) ;
- Felluns (Pyrénées-Orientales) ;
- Pommiers (Loire) ;
- Villosanges (Puy-de-Dôme).

prennent respectivement le nom de :
- Lasserrade ;
- Ports-sur-Vienne ;
- Sainte-Croix-en-Bresse ;
- Laval-en-Belledonne ;
- Saint-Gineys-en-Coiron ;
- Saint-Flour-l'Étang ;
- Montignac-Lascaux ;
- Saint-Mayme-de-Péreyrol ;
- Feilluns ;
- Pommiers-en-Forez ;
- Villossanges.

**Comment by jdesboeufs** [comment]
Le COG 2021 et 2022 ont été mis à jour en début d'année.
