### ISSUE TITLE
Stabiliser le lien vers la BAL

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#793]
Lorsqu'une commune crée une nouvelle BAL, un nouveau lien est généré dans la page : 
https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees
Stabiliser le lien pour qu'en cas de republication, le lien ne change pas.

**Comment by mmortier** [comment]
le lien n'existe plus je clos le ticket
