### ISSUE TITLE
Afficher par défaut la première position connue pour une adresse

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#880]
## Contexte
Un utilisateur a remonté une différence d'affichage concernant la position par défaut d'une adresse affichée sur la carte BAN. [Mes Adresses BaseAdresseNationale/adresse.data.gouv.fr#1036](https://github.com/etalab/editeur-bal/issues/375)

Cette différence rend plus compliqué la lecture des deux cartes mais surtout peut prêter à confusion si l'utilisateur ne fais pas attention au type de la position utilisé.

## Solution proposée
Utiliser la première position connue par défaut ou alors utiliser la position de type `entrée` quand celle-ci est renseignée.

**Comment by GllmR** [comment]
Les données en provenance de l'objet `voie` ne contiennent pas l’information.
Exemple pour le _[348, chemin d’Enc à Rougon](https://adresse.data.gouv.fr/base-adresse-nationale/04171_0011#18.8/43.8008002/6.4041238)_ : 
```javascript
certifie: true
codePostal: "04120"
id: "04171_0011_00348"
libelleAcheminement: "ROUGON"
lieuDitComplementNom: "Saint Joseph"
numero: 348
parcelles: Array [ "041710000B1594" ]
position: Object { type: "Point", coordinates: [ 6.403944, 43.800867 ] }
positionType: "bâtiment"
sourcePosition: "bal"
sources: Array [ "bal" ]
suffixe: null
```

On peut voir que le `positionType` est "bâtiment", alors que nous devrions avoir "entrée".

**Comment by tmerlier** [comment]
Un algorithme de priorisation des positions est en cours de validation sur [ban-plateforme](https://github.com/BaseAdresseNationale/ban-plateforme/pull/22).

Une fois en place, celui-ci devrait permettre un retour homogène des positions. Il ne restera qu'à utiliser cet ordre de priorité sur Mes Adresses pour que les utilisateurs retrouve toujours les positions comme ils les attendent.
