### ISSUE TITLE
Bug d'affichage d'une limite de commune

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#881]
## Contexte
Les limites communales entre les communes de [Béon](https://adresse.data.gouv.fr/base-adresse-nationale/89037#12.98/47.9549/3.31573) et [Montholon](https://adresse.data.gouv.fr/base-adresse-nationale/89003#11.97/47.90152/3.322) ne sont pas affichées sur le fond de carte. Il est donc compliqué de voir où s'arrête la commune de Béon et ou commence la commune sud de Montholon.

Problème sur les données des contours de communes ?

## Ticket original
https://github.com/etalab/editeur-bal/issues/322

**Comment by mmortier** [comment]
@IGNFBourcier on ne l'a pas corrigé ce problème ?

**Comment by IGNFBourcier** [comment]
les deux communes me semblent ok.
doit être lié à #1512 .
