### ISSUE TITLE
Distinguer les sociétés privées dans le résultat de la recherche

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/adresse.data.gouv.fr#882]
## Contexte
Il n'existe pas de distinction entre les organismes de mutualisation et les sociétés privées lors de l'affichage des résultats de la recherche alors que celle-ci existe dans la liste des partenaires.

## Évolutions
- Conserver cette distinction également pour l'affichage des résultat de la recherche.
- Lorsqu'aucun organisme de mutualisation n'est disponible, afficher le message `"Aucun organisme de mutualisation ne couvre votre département. Il est possible qu'il en existe dans le département voisin. Contactez-nous pour vérifier à adresse@data.gouv;fr"`

**Comment by GllmR** [comment]
Fixed by #904
