### ISSUE TITLE
Indiquer le nombre de communes contenues dans chaque BAL

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/adresse.data.gouv.fr#885]
Sur l'écran suivant, il serait pertinent de pouvoir identifier les BAL qui contiennent plusieurs communes, et le nombre de communes concernées.

<img width="897" alt="Capture d’écran 2021-09-16 à 16 15 44" src="https://user-images.githubusercontent.com/1231232/133628329-c02ea821-66a7-4902-bfcf-1d67e606b4e0.png">

**Comment by jdesboeufs** [comment]
Sympa la date de MAJ en 2022.

**Comment by GllmR** [comment]
> Sympa la date de MAJ en 2022.

![image](https://user-images.githubusercontent.com/56537238/133967110-3fcd84a1-cc56-40c5-920e-891b9abbcabc.png)
