### ISSUE TITLE
Modification BAL 1.2 en 1.3 sur le site adresse.data.gouv.fr

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#955]
Sur la page (https://adresse.data.gouv.fr/bases-locales)
Remplacer 1.2 par 1.3 ici : "Les travaux de ce groupe ont abouti à la spécification d’un format d’échange, aujourd’hui en version 1.3."
Lien cassé (404) à remplacer par un lien vers le nouveau PDF : https://aitf-sig-topo.github.io/voies-adresses/files/AITF_SIG_Topo_Format_Base_Adresse_Locale_v1.3.pdf

**Comment by GllmR** [comment]
Fixed by #953
