### ISSUE TITLE
Ajouter Clermont Auvergne Métropole sur la page des Partenaires de la Charte 

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#959]
Clermont Auvergne Métropole

Présentation : 
Clermont Auvergne Métropole accompagne les communes sur un outil mutualisé sur QGIS et Postgis, et assure la publication de leurs Bases Adresses Locales.

Périmètre : Communes de Clermont Auvergne Métropole (département Puy-de-Dome, 63)

Lien : https://www.clermontmetropole.eu/accueil/

Mots-clés : "Formation", "Accompagnement technique", "Réalisation des Bases Adresse Locales", "Mise à disposition d'outil mutualisé"

![Logo_Clermont_Auvergne_Métropole](https://user-images.githubusercontent.com/69309231/144066691-0e7f57b0-6d4d-4505-b4d2-e933307f4232.png)

**Comment by GllmR** [comment]
Fix by #961
