### ISSUE TITLE
Mise à jour du schéma BAN

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/adresse.data.gouv.fr#989]
**Sur la page :** 
https://adresse.data.gouv.fr/donnees-nationales

Le schéma BAN indique en sources SDIS et La Poste.
![Mx6wDM0xD9o9Mbkr](https://user-images.githubusercontent.com/69309231/148353006-fad58959-2aab-483b-a12f-8faeec51fe7c.png)

Or le visualisateur de BAN ne les présente pas.

**Comment by mmortier** [comment]
il s'agit du même ticket que le #997
