### ISSUE TITLE
Erreur proptype invalide sur /publication

### ISSUE THREAD

**Issue by Maxine-Le-Pennec** [BaseAdresseNationale/adresse.data.gouv.fr#990]
Erreur visible en console sur la page /bases-locales/publication

```
Warning: Failed prop type: Invalid prop `Component` of type `object` supplied to `MyApp`, expected `function`.
MyApp@webpack-internal:///./pages/_app.js:41:19
```

**Comment by GllmR** [comment]
Le problème vient du `React.memo`.

`_app` reçoit un objet de type `Symbol("react.memo")` qui fait ensuite référence à la fonction.

@tmerlier Est-ce que ce `memo` est vraiment nécessaire ?

**Comment by Maxine-Le-Pennec** [comment]
> Le problème vient du `React.memo`.
> 
> `_app` reçoit un objet de type `Symbol("react.memo")` qui fait ensuite référence à la fonction.
> 
> @tmerlier Est-ce que ce `memo` est vraiment nécessaire ?

Ouais, j'en ai parlé avec @tmerlier, il m'a dit qu'il allait vérifier mais j'en suis arrivée à la même conclusion

**Comment by jdesboeufs** [comment]
Toujours d'actualité ?
